service_name: "api"
version: "v1.0"
registry: "harbor.lafdru.local"
project: "public/jiffoo-oss"
image_name: "api"
dockerfile_path: "apps/api/Dockerfile"
build_context: "."
gitops_repo: "ops/deploymentrepo"
gitops_branch: "main"
gitops_deployment_path: "jiffoo-oss"
service_port: "3002"
