service_name: "shop"
version: "v1.0"
registry: "harbor.lafdru.local"
project: "public/jiffoo-oss"
image_name: "shop"
dockerfile_path: "apps/shop/Dockerfile"
build_context: "."
gitops_repo: "ops/deploymentrepo"
gitops_branch: "main"
gitops_deployment_path: "jiffoo-oss"
service_port: "3001"
