import openNextWorker from './.open-next/worker.js';

// Generated by OpenNext before Wrangler bundles this entry.
// @ts-ignore The module is absent until the worker build runs.
type AdminEnv = {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
};

export default {
  async fetch(request: Request, env: AdminEnv, ctx: ExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<AdminEnv>;
