import { expect, it } from 'vitest';
import { readFileSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { apiSourceFiles, enumerateModuleState } from '../helpers/module-state-audit';

type Entry = { category: 1 | 2 | 3; reason: string; rebuild?: { file: string; functions: string[] } };

// Every entry is explicit: new names, including persistent class fields, require review.
const codeConstants = [
  'config/api-versions.ts:apiVersionConfig',
  'config/api-versions.ts:versionMetadata',
  'config/env.ts:env',
  'config/env.ts:envSchema',
  'config/logger.ts:loggerConfig',
  'core/account/routes.ts:userProfileSchema',
  'core/account/service.ts:AccountService.profileSelect',
  'core/account/types.ts:UpdateEmailSchema',
  'core/account/types.ts:UpdateProfileSchema',
  'core/admin/audit-events/routes.ts:actorFields',
  'core/admin/audit-events/routes.ts:metadata',
  'core/admin/audit-events/schemas.ts:actorSchema',
  'core/admin/audit-events/schemas.ts:eventSchema',
  'core/admin/audit-events/schemas.ts:filtersSchema',
  'core/admin/audit-events/schemas.ts:pageSchema',
  'core/admin/audit-events/schemas.ts:queryAjv',
  'core/admin/audit-events/schemas.ts:querySchema',
  'core/admin/dashboard/schemas.ts:adminDashboardSchemas',
  'core/admin/dashboard/schemas.ts:dashboardMetricsSchema',
  'core/admin/dashboard/schemas.ts:orderStatusEnum',
  'core/admin/dashboard/schemas.ts:paymentStatusEnum',
  'core/admin/extension-installer/builtin-package.ts:date',
  'core/admin/extension-installer/contract-v1-runtime.ts:contractMethods',
  'core/admin/extension-installer/contract-v1-runtime.ts:requiredMethods',
  'core/admin/extension-installer/gateway-protection.ts:CIRCUIT_BREAKER_CONFIG',
  'core/admin/extension-installer/gateway-protection.ts:RATE_LIMIT_CONFIG',
  'core/admin/extension-installer/index.ts:extensionInstaller',
  'core/admin/extension-installer/marketplace-catalog.ts:apiVersionPattern',
  'core/admin/extension-installer/marketplace-catalog.ts:publisherPattern',
  'core/admin/extension-installer/marketplace-catalog.ts:slugPattern',
  'core/admin/extension-installer/marketplace-catalog.ts:versionPattern',
  'core/admin/extension-installer/payment-webhook-wire.ts:wireSchema',
  'core/admin/extension-installer/plugin-database-audit.ts:DEFAULT_LIMITS',
  'core/admin/extension-installer/plugin-database-audit.ts:PLUGIN_DATABASE_AUDIT_CODES',
  'core/admin/extension-installer/plugin-database-audit.ts:REQUIRED_COLUMNS',
  'core/admin/extension-installer/plugin-database-audit.ts:terminal',
  'core/admin/extension-installer/plugin-fs-installer.ts:BUILTIN_PLUGIN_SLUGS',
  'core/admin/extension-installer/plugin-fs-installer.ts:pluginFsInstaller',
  'core/admin/extension-installer/plugin-migration-gate.ts:INCOMPLETE_PLUGIN_OPERATION_PHASES',
  'core/admin/extension-installer/plugin-migration-gate.ts:RUNNING_PLUGIN_OPERATION_PHASES',
  'core/admin/extension-installer/plugin-migration-gate.ts:pausedPhases',
  'core/admin/extension-installer/plugin-migration-operation.ts:terminal',
  'core/admin/extension-installer/plugin-recovery.ts:TERMINAL_PLUGIN_OPERATION_PHASES',
  'core/admin/extension-installer/plugin-runtime.ts:FORBIDDEN_HEADER_PREFIXES',
  'core/admin/extension-installer/plugin-runtime.ts:INSTANCE_KEY_REGEX',
  'core/admin/extension-installer/plugin-runtime.ts:SLUG_REGEX',
  'core/admin/extension-installer/plugin-runtime.ts:contractMethods',
  'core/admin/extension-installer/plugin-state.ts:resetters',
  'core/admin/extension-installer/routes.ts:PLUGIN_CATEGORIES',
  'core/admin/extension-installer/routes.ts:packageCorruptResponse',
  'core/admin/extension-installer/routes.ts:packageUnavailableResponse',
  'core/admin/extension-installer/schemas.ts:extensionInstallWithUploadSchema',
  'core/admin/extension-installer/schemas.ts:extensionInstallerSchemas',
  'core/admin/extension-installer/schemas.ts:extensionMetaSchema',
  'core/admin/extension-installer/schemas.ts:pluginInstanceSchema',
  'core/admin/extension-installer/schemas.ts:purgePluginResultSchema',
  'core/admin/extension-installer/schemas.ts:restorePluginResultSchema',
  'core/admin/extension-installer/schemas.ts:uninstallPluginResultSchema',
  'core/admin/extension-installer/security.ts:SECURITY_ERROR_MESSAGES',
  'core/admin/extension-installer/theme-home-sections.ts:validators',
  'core/admin/extension-installer/theme-routes.ts:errors',
  'core/admin/extension-installer/theme-routes.ts:params',
  'core/admin/extension-installer/theme-routes.ts:theme',
  'core/admin/extension-installer/theme-runtime.ts:ajv',
  'core/admin/extension-installer/theme-runtime.ts:locales',
  'core/admin/extension-installer/theme-runtime.ts:settingSchemas',
  'core/admin/extension-installer/theme-validator.ts:ajv',
  'core/admin/extension-installer/theme-validator.ts:coreFonts',
  'core/admin/extension-installer/theme-validator.ts:fontPath',
  'core/admin/extension-installer/theme-validator.ts:imagePath',
  'core/admin/extension-installer/theme-validator.ts:safePath',
  'core/admin/extension-installer/theme-validator.ts:validateAdmin',
  'core/admin/extension-installer/theme-validator.ts:validateSections',
  'core/admin/extension-installer/theme-validator.ts:validateShop',
  'core/admin/notifications/routes.ts:detailSchema',
  'core/admin/notifications/routes.ts:listSchema',
  'core/admin/notifications/routes.ts:publicFields',
  'core/admin/notifications/routes.ts:statusValues',
  'core/admin/order-management/schemas.ts:adminOrderDetailSchema',
  'core/admin/order-management/schemas.ts:adminOrderListItemSchema',
  'core/admin/order-management/schemas.ts:adminOrderSchemas',
  'core/admin/order-management/schemas.ts:adminOrderStatsSchema',
  'core/admin/order-management/schemas.ts:orderStatusEnum',
  'core/admin/order-management/schemas.ts:paymentStatusEnum',
  'core/admin/order-management/schemas.ts:shipmentStatusEnum',
  'core/admin/plugin-management/config-crypto.ts:DEVELOPMENT_KEY',
  'core/admin/plugin-management/service.ts:PluginManagementService',
  'core/admin/plugin-management/service.ts:RESERVED_INSTANCE_KEYS',
  'core/admin/plugin-management/service.ts:SLUG_REGEX',
  'core/admin/product-management/schemas.ts:adminProductListItemSchema',
  'core/admin/product-management/schemas.ts:adminProductSchema',
  'core/admin/product-management/schemas.ts:adminProductSchemas',
  'core/admin/product-management/schemas.ts:categorySchema',
  'core/admin/product-management/schemas.ts:deleteProductResultSchema',
  'core/admin/product-management/schemas.ts:productStatsSchema',
  'core/admin/product-management/schemas.ts:productVariantSchema',
  'core/admin/product-management/schemas.ts:translationSchema',
  'core/admin/product-management/schemas.ts:translationsSchema',
  'core/admin/staff-management/routes.ts:adminSchema',
  'core/admin/staff-management/routes.ts:pageSchema',
  'core/admin/staff-management/service.ts:selectAdmin',
  'core/admin/storefront-code/routes.ts:adminSchema',
  'core/admin/storefront-code/schemas.ts:configurationFields',
  'core/admin/storefront-code/schemas.ts:currentSchema',
  'core/admin/storefront-code/schemas.ts:expectedRevision',
  'core/admin/storefront-code/schemas.ts:publicSchema',
  'core/admin/storefront-code/schemas.ts:restoreSchema',
  'core/admin/storefront-code/schemas.ts:revisionSchema',
  'core/admin/storefront-code/schemas.ts:saveSchema',
  'core/admin/storefront-code/schemas.ts:strictBodyAjv',
  'core/admin/storefront-code/schemas.ts:switchSchema',
  'core/admin/storefront-code/service.ts:codeDefaults',
  'core/admin/storefront-code/service.ts:editableFields',
  'core/admin/storefront-code/service.ts:fields',
  'core/admin/system-settings/schemas.ts:adminSettingsSchemas',
  'core/admin/system-settings/schemas.ts:settingValueSchema',
  'core/admin/system-settings/schemas.ts:settingsSchema',
  'core/admin/system-settings/service.ts:DEFAULT_COUNTRIES_REQUIRE_STATE_POSTAL',
  'core/admin/system-settings/service.ts:systemSettingsService',
  'core/admin/user-management/password-reset-link-routes.ts:linkSchema',
  'core/admin/user-management/schemas.ts:adminUserSchemas',
  'core/admin/user-management/schemas.ts:deleteUserResultSchema',
  'core/admin/user-management/schemas.ts:userSchema',
  'core/admin/user-management/schemas.ts:userStatsSchema',
  'core/auth/api-token.ts:ApiTokenService',
  'core/auth/auth-token.ts:durations',
  'core/auth/identity.ts:authIdentitySelect',
  'core/auth/identity.ts:authUserSelect',
  'core/auth/schemas.ts:authResponseSchema',
  'core/auth/schemas.ts:authSchemas',
  'core/auth/schemas.ts:changePasswordResultSchema',
  'core/auth/schemas.ts:logoutResultSchema',
  'core/auth/schemas.ts:userProfileSchema',
  'core/auth/service.ts:authUserSelect',
  'core/auth/types.ts:LoginSchema',
  'core/auth/types.ts:RegisterSchema',
  'core/cache/service.ts:CacheService.PREFIXES',
  'core/cart/schemas.ts:cartItemSchema',
  'core/cart/schemas.ts:cartSchema',
  'core/cart/schemas.ts:cartSchemas',
  'core/cart/schemas.ts:stockErrorSchema',
  'core/checkout/schemas.ts:checkoutSchemas',
  'core/checkout/schemas.ts:quoteResponseSchema',
  'core/checkout/schemas.ts:shippingAddressSchema',
  'core/install/service.ts:RELEASE_VERSION_PATTERN',
  'core/logger/log-aggregator.ts:readdir',
  'core/logger/log-aggregator.ts:stat',
  'core/logger/logger.ts:consoleFormat',
  'core/logger/logger.ts:injectRequestId',
  'core/logger/logger.ts:logFormat',
  'core/logger/unified-logger.ts:LoggerService',
  'core/notifications/delivery.ts:secretPattern',
  'core/notifications/service.ts:notificationLocales',
  'core/notifications/service.ts:translations',
  'core/order/hooks.ts:OrderHooksService.config',
  'core/order/schemas.ts:fulfillmentStatusEnum',
  'core/order/schemas.ts:orderItemResponseSchema',
  'core/order/schemas.ts:orderResponseSchema',
  'core/order/schemas.ts:orderSchemas',
  'core/order/schemas.ts:orderStatusEnum',
  'core/order/schemas.ts:paymentStatusEnum',
  'core/order/schemas.ts:shipmentItemResponseSchema',
  'core/order/schemas.ts:shipmentResponseSchema',
  'core/order/schemas.ts:shipmentStatusEnum',
  'core/order/service.ts:shipmentItemSelect',
  'core/order/service.ts:shipmentSelect',
  'core/order/transition.ts:allowed',
  'core/order/types.ts:CreateOrderSchema',
  'core/order/types.ts:DEFAULT_COUNTRIES_REQUIRE_STATE_POSTAL',
  'core/order/types.ts:OrderItemFulfillmentStatus',
  'core/order/types.ts:OrderItemSchema',
  'core/order/types.ts:OrderStatus',
  'core/order/types.ts:PaymentStatus',
  'core/order/types.ts:ShipmentStatus',
  'core/order/types.ts:ShippingAddressSchema',
  'core/payment/minor-units.ts:CURRENCY_EXPONENTS',
  'core/payment/observations.ts:clearLease',
  'core/payment/reconciliation.ts:clearLease',
  'core/payment/schemas.ts:paymentMethodSchema',
  'core/payment/schemas.ts:paymentSchemas',
  'core/payment/schemas.ts:paymentSessionSchema',
  'core/payment/schemas.ts:paymentVerificationSchema',
  'core/payment/schemas.ts:webhookResponseSchema',
  'core/payment/webhook-routes.ts:mediaTypes',
  'core/product/schemas.ts:categorySchema',
  'core/product/schemas.ts:productDetailSchema',
  'core/product/schemas.ts:productListItemSchema',
  'core/product/schemas.ts:productSchemas',
  'core/product/schemas.ts:productSearchItemSchema',
  'core/product/schemas.ts:productVariantSchema',
  'core/product/types.ts:CreateProductSchema',
  'core/product/types.ts:UpdateProductSchema',
  'core/storage/plugin-package-blob-store.ts:pluginPackageBlobStore',
  'core/storage/plugin-package-store.ts:pluginPackageStore',
  'core/storage/plugin-package-store.ts:themePackageStore',
  'core/storage/theme-package-blob-store.ts:themePackageBlobStore',
  'core/storage/theme-test-hooks.ts:stages',
  'core/storage/uploaded-media-set.ts:fileSchema',
  'core/storage/uploaded-media-set.ts:manifestSchema',
  'core/storage/uploaded-media-set.ts:mediaKeyPattern',
  'core/store/localization.ts:STORE_SUPPORTED_LOCALES',
  'core/store/routes.ts:storeContextSchema',
  'core/upload/service.ts:UploadService.ALLOWED_TYPES',
  'core/upload/service.ts:UploadService.sharpModule',
  'core/user/types.ts:UpdateUserRoleSchema',
  'core/user/types.ts:UpdateUserSchema',
  'infra/events/delivery.ts:EVENT_RETRY_SECONDS',
  'infra/worker-health.ts:WORKER_TASKS',
  'infra/worker-health.ts:workerHeartbeatSchema',
  'plugins/cache-control.ts:CacheControlPresets',
  'plugins/compression.ts:DEFAULT_CONTENT_TYPES',
  'plugins/compression.ts:DevelopmentCompressionConfig',
  'plugins/compression.ts:ProductionCompressionConfig',
  'plugins/compression.ts:brotliCompress',
  'plugins/compression.ts:deflateCompress',
  'plugins/compression.ts:gzipCompress',
  'plugins/rate-limiter.ts:authPolicies',
  'plugins/rate-limiter.ts:exempt',
  'plugins/security-headers.ts:ApiSecurityConfig',
  'server.ts:trustedProxies',
  'types/common-dto.ts:errorResponseSchema',
  'types/common-dto.ts:uploadResultSchema',
  'types/common-dto.ts:validationErrorDetailsSchema',
  'utils/api-errors.ts:connectionCodes',
  'utils/api-errors.ts:definition',
  'utils/api-errors.ts:errorCatalog',
  'utils/error-schemas.ts:pluginGatewayPath',
  'utils/i18n.ts:LOCALES',
  'utils/schema-helpers.ts:commonResponseSchemas',
  'utils/schema-helpers.ts:errorResponseSchema',
  'utils/schema-helpers.ts:successResponseSchema',
] as const;
const runtimeHandles = [
  'config/database.ts:prisma',
  'core/admin/extension-installer/plugin-database-audit.ts:testLimits',
  'core/admin/extension-installer/plugin-database-audit.ts:testMigrationRoot',
  'core/admin/extension-installer/plugin-database-audit.ts:testSchema',
  'core/admin/extension-installer/plugin-database-queue.ts:PluginDatabaseQueue.active',
  'core/admin/extension-installer/plugin-database-queue.ts:PluginDatabaseQueue.rotation',
  'core/admin/extension-installer/plugin-database-queue.ts:PluginDatabaseQueue.waiting',
  'core/admin/extension-installer/plugin-database-test-control.ts:controls',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.active',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.clients',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.closeWork',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.pool',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.poolEndWork',
  'core/admin/extension-installer/plugin-database.ts:PluginDatabaseRuntime.queue',
  'core/admin/extension-installer/plugin-database.ts:failures',
  'core/admin/extension-installer/plugin-database.ts:invocations',
  'core/admin/extension-installer/plugin-database.ts:runtime',
  'core/admin/extension-installer/plugin-database.ts:scopes',
  'core/admin/extension-installer/plugin-database.ts:transactions',
  'core/admin/extension-installer/plugin-migration-operation.ts:migrationSlots',
  'core/admin/extension-installer/plugin-migration-operation.ts:running',
  'core/admin/extension-installer/plugin-recovery-test-control.ts:controls',
  'core/admin/extension-installer/plugin-recovery.ts:cursor',
  'core/admin/extension-installer/plugin-registry-freshness.ts:inFlight',
  'core/admin/extension-installer/plugin-runtime.ts:contractInvocations',
  'core/admin/plugin-management/config-crypto.ts:warned',
  'core/cache/redis.ts:RedisCache.instance',
  'core/cache/redis.ts:RedisCache.redis',
  'core/cache/redis.ts:redisCache',
  'core/logger/log-aggregator.ts:logAggregator',
  'core/logger/logger.ts:logger',
  'core/logger/logger.ts:transports',
  'core/logger/trace-context.ts:traceStorage',
  'core/logger/unified-logger.ts:logger',
  'core/logger/unified-logger.ts:unifiedLogger',
  'core/notifications/delivery.ts:claimed',
  'core/notifications/delivery.ts:client',
  'core/notifications/delivery.ts:running',
  'core/order/hooks.ts:OrderHooksService.prisma',
  'core/order/hooks.ts:orderHooksInstance',
  'core/payment/clock.ts:clock',
  'core/payment/locks.ts:observers',
  'core/payment/reconciliation.ts:client',
  'core/payment/session-test-control.ts:controls',
  'core/storage/completed-plugin-markers.ts:completed',
  'core/storage/current-plugin-package.ts:active',
  'core/storage/current-plugin-package.ts:pending',
  'core/storage/current-plugin-package.ts:waiting',
  'core/storage/current-theme-package.ts:active',
  'core/storage/current-theme-package.ts:pending',
  'core/storage/current-theme-package.ts:waiting',
  'core/storage/uploaded-object-store.ts:S3UploadedObjectStore.client',
  'core/storage/uploaded-object-store.ts:uploadedObjectStore',
  'infra/core-process-identity.ts:coreProcessIdentity',
  'infra/core-process.ts:heartbeat',
  'infra/core-process.ts:pending',
  'infra/core-process.ts:registration',
  'infra/events/delivery.ts:EventDeliveryEngine.claimOperation',
  'infra/events/delivery.ts:EventDeliveryEngine.installations',
  'infra/events/delivery.ts:EventDeliveryEngine.invocations',
  'infra/events/delivery.ts:EventDeliveryEngine.pending',
  'infra/events/delivery.ts:EventDeliveryEngine.timer',
  'infra/events/delivery.ts:testHandlerTimeoutMs',
  'infra/prisma-slow-query-extension.ts:lastCleanupAt',
  'infra/prisma-slow-query-extension.ts:recentLogs',
  'infra/prisma-slow-query-extension.ts:slowQueryExtension',
  'infra/shared-protection.ts:SharedProtection.client',
  'infra/shared-protection.ts:SharedProtection.connecting',
  'infra/shared-protection.ts:sharedProtection',
  'infra/worker-shutdown.ts:testDeadlineMs',
  'infra/worker-shutdown.ts:testObserver',
  'jobs/payment-reconciliation.ts:PaymentReconciliationJob.options',
  'jobs/payment-reconciliation.ts:PaymentReconciliationJob.isRunning',
  'jobs/payment-reconciliation.ts:PaymentReconciliationJob.pending',
  'jobs/payment-reconciliation.ts:PaymentReconciliationJob.updateInterval',
  'server.ts:fastify',
] as const;
const pluginState: Record<string, Entry> = {
  'core/admin/extension-installer/contract-v1-runtime.ts:eventHandlers': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-runtime.ts', functions: ["dropInternalRuntime","clearContractV1EventHandlers"] } },
  'core/admin/extension-installer/plugin-runtime.ts:internalRuntimes': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-runtime.ts', functions: ["dropInternalRuntime","warmPluginInstanceRuntime"] } },
  'core/admin/extension-installer/plugin-failure.ts:lastRecordedAt': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-failure.ts', functions: ["registerPluginStateReset","lastRecordedAt.delete"] } },
  'core/admin/extension-installer/plugin-module-loader.ts:runtimeRequire': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-module-loader.ts', functions: ["loadPluginEntryModule","delete runtimeRequire.cache"] } },
  'core/storage/current-plugin-package.ts:corrupt': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/storage/current-plugin-package.ts', functions: ["setPluginPackageRegistryVersion","corrupt.clear"] } },
  'core/storage/current-plugin-package.ts:registryVersion': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/storage/current-plugin-package.ts', functions: ["setPluginPackageRegistryVersion","corrupt.clear"] } },
  'core/admin/extension-installer/plugin-registry-freshness.ts:reconciledVersion': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-registry-freshness.ts', functions: ["ensurePluginRegistryFresh","reconcileAllPluginState"] } },
  'core/admin/extension-installer/plugin-registry-freshness.ts:resetEpoch': { category: 1, reason: 'Registry-version reconciliation resets and rebuilds plugin-derived state.', rebuild: { file: 'core/admin/extension-installer/plugin-registry-freshness.ts', functions: ["resetPluginRegistryFreshness","reconciledVersion = null"] } },
};
const allowlist: Record<string, Entry> = {
  ...Object.fromEntries(codeConstants.map(name => [name, { category: 3, reason: 'Code-defined schema, policy, validator, stateless service or immutable configuration; no retained request data.' }])),
  ...Object.fromEntries(runtimeHandles.map(name => [name, { category: 2, reason: 'Process runtime handle, async-local scope, bounded code-model diagnostic timing, or in-flight work bookkeeping; no cached user, IP, session or order payload.' }])),
  ...pluginState,
};

it('Scenarios 12 and 15 enumerate every module container and reject new unreviewed state', () => {
  const entries = enumerateModuleState(apiSourceFiles());
  expect(entries).toEqual(Object.keys(allowlist).sort());
  expect(new Set([...codeConstants, ...runtimeHandles, ...Object.keys(pluginState)]).size).toBe(entries.length);
  for (const entry of Object.values(allowlist)) {
    expect([1, 2, 3]).toContain(entry.category);
    expect(entry.reason.trim()).not.toBe('');
    if (entry.category === 1) {
      expect(entry.rebuild).toBeDefined();
      const code = readFileSync(path.resolve('src', entry.rebuild!.file), 'utf8');
      for (const name of entry.rebuild!.functions) expect(code).toContain(name);
    }
  }
  const reconciliation = readFileSync(path.resolve('src/core/admin/extension-installer/plugin-reconciliation.ts'), 'utf8');
  expect(reconciliation).toContain('await resetPluginState(slug)');
  expect(reconciliation).toContain('await warmPluginInstanceRuntime(slug, installation.id)');
  const freshness = readFileSync(path.resolve('src/core/admin/extension-installer/plugin-registry-freshness.ts'), 'utf8');
  expect(freshness).toContain('setPluginPackageRegistryVersion(version)');
  expect(freshness).toContain('reconcileAllPluginState()');
});

it('the audit detects multiline containers, inferred factories, mutable scalars and class state while excluding request locals', () => {
  const root = mkdtempSync(path.join(os.tmpdir(), 'jiffoo-state-audit-'));
  const file = path.join(root, 'sample.ts');
  try {
    writeFileSync(file, `const map =
      new Map<string, string>();
      const weak = new WeakMap<object, object>();
      const items: string[] = [];
      const factory = Object.assign({}, { value: 1 });
      let cursor: string | undefined;
      class Singleton { static users = new Set<string>(); }
      function request() { const local = new Map(); let user = ''; return local; }
    `, 'utf8');
    expect(enumerateModuleState([file], root)).toEqual([
      'sample.ts:Singleton.users', 'sample.ts:cursor', 'sample.ts:factory',
      'sample.ts:items', 'sample.ts:map', 'sample.ts:weak',
    ]);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

