# PostgreSQL部署到K3s集群

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: jiffoo-system
data:
  POSTGRES_DB: jiffoo_dev
  POSTGRES_USER: jiffoo
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jiffoo-system
type: Opaque
data:
  POSTGRES_PASSWORD: WU9VUl9QQVNTV09SRA==  # base64 encoded "jiffoo123"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: jiffoo-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: jiffoo-system
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: jiffoo-system
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
# 注意：请修改 POSTGRES_PASSWORD 为你自己的密码（base64 编码）
