import { proxyApiRequest } from './lib/cloudflare/api-proxy';
import { addBuildProvenance } from './lib/cloudflare/build-provenance';
import { serveThemeAsset } from './lib/cloudflare/theme-assets';

// Generated by OpenNext before Wrangler bundles this entry.
// @ts-ignore The module is absent until `build:cloudflare` runs.
import openNextWorker from './.open-next/worker.js';

type ShopEnv = {
  ASSETS: {
    fetch(request: Request): Promise<Response>;
  };
  THEME_ASSETS: R2Bucket;
  API_SERVICE_URL: string;
};

export default {
  async fetch(request: Request, env: ShopEnv, ctx: ExecutionContext): Promise<Response> {
    const themeAsset = await serveThemeAsset(request, env.THEME_ASSETS);
    if (themeAsset) return themeAsset;

    const apiResponse = await proxyApiRequest(request, env.API_SERVICE_URL);
    if (apiResponse) return apiResponse;

    const response = await openNextWorker.fetch(request, env, ctx);
    return addBuildProvenance(request, response, env.ASSETS);
  },
} satisfies ExportedHandler<ShopEnv>;
