/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--shop-canvas)',
        surface: 'var(--shop-surface)',
        ink: 'var(--shop-ink)',
        subtle: 'var(--shop-subtle)',
        line: 'var(--shop-line)',
        action: 'var(--shop-action)',
        'action-ink': 'var(--shop-action-ink)',
        highlight: 'var(--shop-highlight)',
        background: 'var(--shop-background)',
        'surface-muted': 'var(--shop-surface-muted)',
        'text-muted': 'var(--shop-text-muted)',
        border: 'var(--shop-border)',
        primary: 'var(--shop-primary)',
        'primary-foreground': 'var(--shop-primary-foreground)',
        secondary: 'var(--shop-secondary)',
        'secondary-foreground': 'var(--shop-secondary-foreground)',
        accent: 'var(--shop-accent)',
        success: 'var(--shop-success)',
        warning: 'var(--shop-warning)',
        danger: 'var(--shop-danger)',
        'header-bg': 'var(--shop-header-bg)',
        'header-text': 'var(--shop-header-text)',
        'footer-bg': 'var(--shop-footer-bg)',
        'footer-text': 'var(--shop-footer-text)',
        'announcement-bg': 'var(--shop-announcement-bg)',
        'announcement-text': 'var(--shop-announcement-text)',
        price: 'var(--shop-price)',
        'sale-price': 'var(--shop-sale-price)',
      },
      fontFamily: { sans: 'var(--shop-font-body)', heading: 'var(--shop-font-heading)' },
      fontSize: { 'shop-base': 'var(--shop-font-size-base)' },
      borderRadius: {
        shop: 'var(--shop-radius-md)', 'shop-sm': 'var(--shop-radius-sm)',
        'shop-lg': 'var(--shop-radius-lg)', button: 'var(--shop-button-radius)',
        card: 'var(--shop-card-radius)',
      },
      spacing: { section: 'var(--shop-section-spacing)' },
      maxWidth: { container: 'var(--shop-container-width)' },
      fontWeight: { heading: 'var(--shop-heading-weight)' },
      boxShadow: { card: 'var(--shop-card-shadow)' },
      scale: { shop: 'var(--shop-type-scale)' },
    },
  },
  plugins: [],
};
