name = "bokmoo-shop"
main = ".open-next/worker.js"
compatibility_date = "2026-07-12"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true
preview_urls = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_API_URL = "https://api.bokmoo.com/api"
API_SERVICE_URL = "https://api.bokmoo.com"
SERVER_STORE_CONTEXT_TIMEOUT_MS = "2000"
THEME_APP_PROXY_DISABLED = "1"
THEME_APP_PROXY_TIMEOUT_MS = "1000"
NEXT_PUBLIC_FALLBACK_STORE_NAME = "Bokmoo"
NEXT_PUBLIC_FALLBACK_THEME_SLUG = "bokmoo"
NEXT_PUBLIC_FALLBACK_THEME_VERSION = "1.1.3"
NEXT_PUBLIC_FALLBACK_DEFAULT_LOCALE = "en"
NEXT_PUBLIC_FALLBACK_SUPPORTED_LOCALES = "en,zh-Hant"
NEXT_PUBLIC_FALLBACK_POWERED_BY_JIFFOO = "0"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "bokmoo-shop"
