/**
 * Model Usage Audit Script (Task 3.1.1)
 *
 * Parses all .prisma files in the schema/ directory to extract model names, then greps
 * apps/api/src for `prisma.<modelName>` references and type imports
 * to classify each model as "active" or "dormant".
 *
 * Usage:
 *   node scripts/audit-model-usage.cjs
 *   # or
 *   pnpm --filter api exec tsx scripts/audit-model-usage.ts
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, extname } from 'path';

// ============================================================================
// Configuration
// ============================================================================

const SCHEMA_DIR = join(__dirname, '..', 'prisma', 'schema');
const SRC_DIR = join(__dirname, '..', 'src');
const SCAN_EXTENSIONS = ['.ts', '.tsx'];

// ============================================================================
// 1. Parse all .prisma files in schema/ directory for model names
// ============================================================================

function parseModels(schemaDir: string): string[] {
  const models: string[] = [];
  const regex = /^model\s+(\w+)\s+\{/gm;
  // Read all .prisma files in the schema directory
  for (const file of readdirSync(schemaDir)) {
    if (file.endsWith('.prisma')) {
      const content = readFileSync(join(schemaDir, file), 'utf-8');
      let match: RegExpExecArray | null;
      while ((match = regex.exec(content)) !== null) {
        models.push(match[1]);
      }
    }
  }
  return models.sort();
}

// ============================================================================
// 2. Scan source files for references
// ============================================================================

function getAllTsFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      results.push(...getAllTsFiles(fullPath));
    } else if (SCAN_EXTENSIONS.includes(extname(fullPath))) {
      results.push(fullPath);
    }
  }
  return results;
}

interface ModelReference {
  model: string;
  files: string[];
  /** prisma.modelName occurrences */
  prismaRefs: number;
  /** Type import occurrences (import ... ModelName) */
  typeRefs: number;
}

function scanReferences(models: string[], srcDir: string): Map<string, ModelReference> {
  const files = getAllTsFiles(srcDir);
  const refs = new Map<string, ModelReference>();

  console.log(`Scanning ${files.length} TS files in ${srcDir}`);

  for (const model of models) {
    refs.set(model, { model, files: [], prismaRefs: 0, typeRefs: 0 });
  }

  for (const file of files) {
    const content = readFileSync(file, 'utf-8');
    const relPath = file.replace(srcDir + '/', '');

    for (const model of models) {
      const ref = refs.get(model)!;

      // Count prisma.modelName references (construct fresh regex per file to avoid stateful lastIndex)
      const prismaPattern = `prisma.${model}`;
      const prismaMatches = content.split(prismaPattern).length - 1;
      if (prismaMatches > 0) {
        ref.prismaRefs += prismaMatches;
        if (!ref.files.includes(relPath)) {
          ref.files.push(relPath);
        }
      }

      // Count type references (only in files that import from @prisma/client)
      if (content.includes('@prisma/client') || content.includes('PrismaClient')) {
        const typeRegex = new RegExp(`\\b${model}\\b`, 'g');
        const typeMatches = content.match(typeRegex);
        if (typeMatches && typeMatches.length > 0) {
          ref.typeRefs += typeMatches.length;
        }
      }
    }
  }

  return refs;
}

// ============================================================================
// 3. Output report
// ============================================================================

function classifyModel(ref: ModelReference): 'active' | 'dormant' {
  if (ref.prismaRefs > 0) return 'active';
  if (ref.typeRefs > 1) return 'active'; // More than 1 word match = likely real type usage
  if (ref.typeRefs === 1 && ref.files.length > 0) return 'active';
  return 'dormant';
}

function generateReport(refs: Map<string, ModelReference>): string {
  const lines: string[] = [];
  lines.push('# Model Usage Audit Report');
  lines.push('');
  lines.push('> Generated by `scripts/audit-model-usage.ts` (Task 3.1.1)');
  lines.push('> Scans `prisma/schema/` models and `apps/api/src/` for Prisma client references.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');

  const active: ModelReference[] = [];
  const dormant: ModelReference[] = [];
  for (const ref of refs.values()) {
    if (classifyModel(ref) === 'active') {
      active.push(ref);
    } else {
      dormant.push(ref);
    }
  }

  lines.push(`| Category | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Active   | ${active.length} |`);
  lines.push(`| Dormant  | ${dormant.length} |`);
  lines.push(`| **Total**| **${active.length + dormant.length}** |`);
  lines.push('');

  lines.push('## Active Models');
  lines.push('');
  lines.push(`| # | Model | prisma.* refs | Type refs | Files |`);
  lines.push(`|---|-------|--------------|-----------|-------|`);
  active.forEach((ref, i) => {
    lines.push(`| ${i + 1} | \`${ref.model}\` | ${ref.prismaRefs} | ${ref.typeRefs} | ${ref.files.length} |`);
  });
  lines.push('');

  lines.push('## Dormant Models');
  lines.push('');
  if (dormant.length === 0) {
    lines.push('No dormant models found.');
  } else {
    lines.push(`| # | Model | prisma.* refs | Type refs | Files |`);
    lines.push(`|---|-------|--------------|-----------|-------|`);
    dormant.forEach((ref, i) => {
      lines.push(`| ${i + 1} | \`${ref.model}\` | ${ref.prismaRefs} | ${ref.typeRefs} | ${ref.files.length} |`);
    });
  }
  lines.push('');

  lines.push('## Dormant Model Details');
  lines.push('');
  for (const ref of dormant) {
    lines.push(`### \`${ref.model}\``);
    lines.push(`- prisma.* references: ${ref.prismaRefs}`);
    lines.push(`- Type references: ${ref.typeRefs}`);
    lines.push(`- Files: ${ref.files.length > 0 ? ref.files.join(', ') : 'none'}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// Main
// ============================================================================

function main(): void {
  console.log('Parsing prisma/schema/ directory...');
  const models = parseModels(SCHEMA_DIR);
  console.log(`Found ${models.length} models: ${models.join(', ')}`);

  console.log('\nScanning apps/api/src for references...');
  const refs = scanReferences(models, SRC_DIR);

  const report = generateReport(refs);

  // Output to stdout and also write to spec directory
  const outputPath = join(__dirname, '..', '..', '..', '.kiro', 'specs', 'platform-evolution-2026h2', 'model-audit.md');
  const { writeFileSync } = require('fs');
  writeFileSync(outputPath, report, 'utf-8');
  console.log(`\nReport written to: ${outputPath}`);
  console.log(`\n${report}`);
}

main();
