import type { Locale, TranslationFunction } from '../types';
import { themeText as sdkThemeText } from 'jiffoo-theme-api-sdk';

type MessageKey = string;

export const themeMessages: Record<Locale, Record<MessageKey, string>> = {
  en: {
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.downloadApk': 'Download APK',
    'auth.login.subtitle': 'Sign in to your account', 'auth.register.subtitle': 'Create your account', 'auth.email': 'Email Address', 'auth.password': 'Password', 'auth.firstName': 'First Name', 'auth.lastName': 'Last Name', 'auth.confirmPassword': 'Confirm Password', 'auth.passwordMismatch': 'Passwords do not match', 'auth.signIn': 'Sign In', 'auth.signUp': 'Sign up', 'auth.createAccount': 'Create Account', 'auth.forgotPassword': 'Forgot password?', 'auth.orContinue': 'Or continue with', 'auth.orSignUp': 'Or sign up with', 'auth.google': 'Continue with Google', 'auth.hidePassword': 'Hide password', 'auth.showPassword': 'Show password',
    'nav.features': 'Features', 'nav.security': 'Security', 'nav.download': 'Download',
    'orders.placedOn': 'Placed on', 'orders.buyNew': 'Buy New eSIM', 'orders.active': 'Active', 'orders.upcoming': 'Upcoming', 'orders.expired': 'Expired', 'orders.all': 'All', 'orders.errorTitle': 'Something went wrong', 'orders.home': 'Home', 'orders.account': 'My Account', 'orders.emptyTitle': 'No eSIMs Found', 'orders.emptyDescription': "You don't have any eSIMs in this category yet.", 'orders.browsePackages': 'Browse Packages', 'orders.ordered': 'Ordered:', 'orders.status': 'Status:', 'orders.dataUsage': 'Data Usage', 'orders.daysRemaining': '{days} days remaining', 'orders.topUp': 'Top Up Data', 'orders.showQr': 'Show QR Code', 'orders.speed': 'Speed', 'orders.highSpeed': '4G/5G High-Speed', 'orders.network': 'Network', 'orders.majorCarriers': 'Major Carriers', 'orders.support': 'Support', 'orders.available247': '24/7 Available', 'orders.manageSettings': 'Manage Settings', 'orders.deviceInstructions': 'Device Instructions', 'orders.getSupport': 'Get Support', 'orders.viewReceipt': 'View Receipt', 'orders.prev': 'Prev', 'orders.next': 'Next', 'orders.helpTitle': 'Need help with your eSIM?', 'orders.helpDescription': 'Our support team is available 24/7 to help you with any issues regarding your eSIM activation, data usage, or technical problems.', 'orders.contactSupport': 'Contact Support', 'orders.viewFaq': 'View FAQ',
    'orderDetail.notFound': 'Order Not Found', 'orderDetail.notFoundDescription': 'The order you are looking for does not exist.', 'orderDetail.backToOrders': 'Back to Orders', 'orderDetail.activationProgress': 'eSIM Activation Progress', 'orderDetail.orderPlaced': 'Order Placed', 'orderDetail.paymentConfirmed': 'Payment Confirmed', 'orderDetail.provisioned': 'eSIM Provisioned', 'orderDetail.qrSent': 'QR Code Sent', 'orderDetail.activated': 'Activated', 'orderDetail.packages': 'eSIM Packages', 'orderDetail.qty': 'Qty: {quantity}', 'orderDetail.each': '${amount} each', 'orderDetail.subtotal': 'Subtotal', 'orderDetail.delivery': 'Delivery', 'orderDetail.instantEmail': 'Instant (Email)', 'orderDetail.total': 'Total', 'orderDetail.quickActions': 'Quick Actions', 'orderDetail.viewQr': 'Show QR Code', 'orderDetail.cancelTitle': 'Cancel Order', 'orderDetail.cancelDescription': 'If you no longer need this eSIM, you can cancel the order for a full refund.', 'orderDetail.cancel': 'Cancel Order', 'orderDetail.backToEsims': 'Back to My eSIMs',
    'orderSuccess.title': 'eSIM Order Confirmed!', 'orderSuccess.subtitle': 'Your eSIM package is being prepared for activation.', 'orderSuccess.orderNumber': 'Order Number', 'orderSuccess.paymentProcessed': 'Your payment has been processed successfully', 'orderSuccess.emailSent': 'eSIM QR code and activation instructions sent to your email', 'orderSuccess.scanQr': 'Scan the QR code with your device to install the eSIM profile', 'orderSuccess.howToActivate': 'How to Activate Your eSIM', 'orderSuccess.checkEmail': 'Check Your Email', 'orderSuccess.checkEmailDescription': "You'll receive an email with your eSIM QR code within minutes", 'orderSuccess.scanQrTitle': 'Scan QR Code', 'orderSuccess.scanQrDescription': 'Go to Settings > Cellular > Add eSIM and scan the QR code', 'orderSuccess.activateDestination': 'Activate at Destination', 'orderSuccess.activateDestinationDescription': 'Turn on data roaming when you arrive — your eSIM connects automatically', 'orderSuccess.viewEsims': 'View My eSIMs', 'orderSuccess.browsePackages': 'Browse More Packages',
    'orderCancelled.title': 'Payment Cancelled', 'orderCancelled.subtitle': 'Your payment was cancelled. No charges were made to your account.', 'orderCancelled.cartSaved': 'Your cart is still saved', 'orderCancelled.cartSavedDescription': 'All eSIM packages remain in your cart and you can complete your purchase anytime', 'orderCancelled.needHelp': 'Need help?', 'orderCancelled.needHelpDescription': 'If you encountered any issues during checkout, our support team is available 24/7', 'orderCancelled.whatHappened': 'What Happened?', 'orderCancelled.whatHappenedDescription': 'You cancelled the payment process before completing your eSIM order. This could happen if you:', 'orderCancelled.reasonBack': 'Clicked the back button during checkout', 'orderCancelled.reasonClosed': 'Closed the payment window', 'orderCancelled.reasonReview': 'Decided to review your eSIM selection again', 'orderCancelled.reasonIssue': 'Encountered a technical issue', 'orderCancelled.returnCart': 'Return to Cart', 'orderCancelled.browsePackages': 'Browse Packages', 'orderCancelled.assistance': 'Need assistance?', 'orderCancelled.contactSupport': 'Contact Support',
    'checkout.home': 'Home', 'checkout.packages': 'eSIM Packages', 'checkout.title': 'Checkout', 'checkout.account': 'Account Information', 'checkout.device': 'Device Information', 'checkout.traveler': 'Traveler Information', 'checkout.payment': 'Payment Method', 'checkout.summary': 'Order Summary',
    'checkout.loginPrompt': 'Already have an account?', 'checkout.login': 'Log in', 'checkout.email': 'Email Address', 'checkout.emailDelivery': 'Your eSIM will be delivered to this email address', 'checkout.deviceType': 'Device Type', 'checkout.selectDevice': 'Select your device type', 'checkout.iphone': 'iPhone (XR or newer)', 'checkout.samsung': 'Samsung Galaxy (S20 or newer)', 'checkout.pixel': 'Google Pixel (3 or newer)', 'checkout.ipad': 'iPad (7th gen or newer)', 'checkout.otherDevice': 'Other eSIM Compatible Device', 'checkout.osVersion': 'iOS / Android Version', 'checkout.compatibility': 'Make sure your device is eSIM compatible. Most modern smartphones support eSIM technology.', 'checkout.checkCompatibility': 'Check device compatibility', 'checkout.firstName': 'First Name', 'checkout.lastName': 'Last Name', 'checkout.phone': 'Phone Number', 'checkout.travelDate': 'Travel Date', 'checkout.card': 'Credit/Debit Card', 'checkout.cardNumber': 'Card Number', 'checkout.expiry': 'Expiry Date', 'checkout.cvc': 'CVC/CVV', 'checkout.saveCard': 'Save this card for future purchases', 'checkout.agree': 'I agree to the', 'checkout.and': 'and', 'checkout.subtotal': 'Subtotal', 'checkout.tax': 'Tax', 'checkout.discount': 'Discount', 'checkout.total': 'Total', 'checkout.promo': 'Promo Code', 'checkout.enterCode': 'Enter code', 'checkout.apply': 'Apply', 'checkout.processing': 'Processing...', 'checkout.complete': 'Complete Purchase', 'checkout.deliveryNote': "You'll receive your eSIM via email immediately after purchase", 'checkout.error.emailRequired': 'Email is required', 'checkout.error.emailFormat': 'Invalid email format', 'checkout.error.firstName': 'First name is required', 'checkout.error.lastName': 'Last name is required', 'checkout.error.address': 'Address is required', 'checkout.error.city': 'City is required', 'checkout.error.state': 'State is required', 'checkout.error.postal': 'Postal code is required', 'checkout.error.country': 'Country is required', 'checkout.error.phone': 'Phone number is required',
    'product.notFound': 'Product Not Found', 'product.notFoundDescription': 'The eSIM package you are looking for does not exist.', 'product.features': 'Key Features', 'product.description': 'Description', 'product.reviews': 'Customer Reviews', 'product.choosePlan': 'Choose Your Plan', 'product.quantity': 'Quantity', 'product.needHelp': 'Need Help?',
    'product.goBack': 'Go Back', 'product.new': 'New', 'product.reviewsCount': '{count} reviews', 'product.data': 'Data', 'product.validity': 'Validity', 'product.network': 'Network', 'product.coverage': '4G/5G Coverage', 'product.defaultData': '5GB High-Speed Data', 'product.defaultValidity': '30 Days', 'product.descriptionBody': 'Stay connected wherever you go with our premium eSIM service. Enjoy seamless connectivity with high-speed data, easy setup, and reliable coverage across major networks.', 'product.basedOn': 'Based on {count} reviews', 'product.star': 'star', 'product.stars': 'stars', 'product.seeAll': 'See All {count} Reviews', 'product.outOfStock': 'Out of Stock', 'product.inStock': 'In Stock', 'product.taxesIncluded': 'Taxes included', 'product.buyNow': 'Buy Now', 'product.addToCart': 'Add to Cart', 'product.secure': 'Secure transaction', 'product.instantDelivery': 'Instant delivery via email', 'product.refund': '7-day refund policy if not activated', 'product.supportBody': 'Our support team is available 24/7 to assist you with any questions.', 'product.chatSupport': 'Chat with Support', 'product.alsoLike': 'You May Also Like', 'product.bestSeller': 'Best Seller', 'product.viewDetails': 'View Details',
    'travelpass.cart.title': 'Shopping Cart', 'travelpass.cart.empty': 'Your cart is empty', 'travelpass.cart.emptyDescription': 'Browse our eSIM packages to get started', 'travelpass.cart.continueShopping': 'Continue Shopping', 'travelpass.cart.orderSummary': 'Order Summary', 'travelpass.cart.total': 'Total', 'travelpass.cart.checkout': 'Proceed to Checkout',
    'travelpass.help.title': 'Help Center', 'travelpass.help.subtitle': 'Find answers to common questions about eSIM activation, data usage, and more',
    'travelpass.contact.title': 'eSIM Support', 'travelpass.contact.subtitle': 'Our team is available 24/7 to help with activation, connectivity, or billing',
    'legal.privacy.title': 'Privacy Policy', 'legal.terms.title': 'Terms of Service', 'legal.lastUpdated': 'Last updated: {date}',
    'appDownload.mobile.download': 'Download',
    'appDownload.hero.eyebrow': 'EasyEUICC for Android',
    'appDownload.hero.title': 'Download EasyEUICC',
    'appDownload.hero.noAds': 'No ads',
    'appDownload.hero.profileManagement': 'eUICC management',
    'appDownload.hero.directInstall': 'Direct APK install',
    'appDownload.download.scan': 'Scan or click to download the latest APK',
    'appDownload.download.currentVersion': 'Current version {version}.',
    'appDownload.download.androidRecommendation': 'Android 9+ recommended. Verify the signature and checksum after downloading.',
    'appDownload.tools.title': 'Profile tools',
    'appDownload.tools.ready': 'Ready',
    'appDownload.tools.scan.title': 'Scan activation code',
    'appDownload.tools.scan.meta': 'Camera and manual entry',
    'appDownload.tools.switch.title': 'Switch active profile',
    'appDownload.tools.switch.meta': 'Fast profile control',
    'appDownload.tools.storage.title': 'Local profile storage',
    'appDownload.tools.storage.meta': 'Device-first management',
    'appDownload.tools.latestPackage': 'Latest package',
    'appDownload.features.manage.title': 'Profile management',
    'appDownload.features.manage.body': 'View, enable, and maintain eSIM profiles on your device.',
    'appDownload.features.scan.title': 'Scan to add',
    'appDownload.features.scan.body': 'Add activation data quickly with a QR code or manual entry.',
    'appDownload.features.local.title': 'Local first',
    'appDownload.features.local.body': 'Core management actions run on the device with fewer dependencies.',
    'appDownload.features.control.title': 'Stay in control',
    'appDownload.features.control.body': 'Keep critical operations on the device and reduce external reliance.',
    'appDownload.security.eyebrow': 'Secure download',
    'appDownload.security.title': 'Only the confirmed latest Android package is provided.',
    'appDownload.security.version': 'Version: {version}',
    'appDownload.security.package': 'Package: im.angry.easyeuicc',
    'appDownload.security.targetSdk': 'Target SDK: 35',
  },
  'zh-Hans': {
    'common.privacy': '隐私政策',
    'common.terms': '服务条款',
    'common.downloadApk': '下载 APK',
    'auth.login.subtitle': '登录您的账户', 'auth.register.subtitle': '创建您的账户', 'auth.email': '电子邮箱', 'auth.password': '密码', 'auth.firstName': '名', 'auth.lastName': '姓', 'auth.confirmPassword': '确认密码', 'auth.passwordMismatch': '两次输入的密码不一致', 'auth.signIn': '登录', 'auth.signUp': '注册', 'auth.createAccount': '创建账户', 'auth.forgotPassword': '忘记密码？', 'auth.orContinue': '或使用以下方式继续', 'auth.orSignUp': '或使用以下方式注册', 'auth.google': '使用 Google 继续', 'auth.hidePassword': '隐藏密码', 'auth.showPassword': '显示密码',
    'nav.features': '功能', 'nav.security': '安全', 'nav.download': '下载',
    'orders.placedOn': '下单时间：', 'orders.buyNew': '购买新 eSIM', 'orders.active': '进行中', 'orders.upcoming': '即将开始', 'orders.expired': '已结束', 'orders.all': '全部', 'orders.errorTitle': '发生错误', 'orders.home': '首页', 'orders.account': '我的账户', 'orders.emptyTitle': '未找到 eSIM', 'orders.emptyDescription': '此分类下暂时没有 eSIM。', 'orders.browsePackages': '浏览套餐', 'orders.ordered': '下单时间：', 'orders.status': '状态：', 'orders.dataUsage': '流量使用', 'orders.daysRemaining': '剩余 {days} 天', 'orders.topUp': '充值流量', 'orders.showQr': '显示二维码', 'orders.speed': '网速', 'orders.highSpeed': '4G/5G 高速', 'orders.network': '网络', 'orders.majorCarriers': '主流运营商', 'orders.support': '支持', 'orders.available247': '全天候可用', 'orders.manageSettings': '管理设置', 'orders.deviceInstructions': '设备说明', 'orders.getSupport': '获取支持', 'orders.viewReceipt': '查看收据', 'orders.prev': '上一页', 'orders.next': '下一页', 'orders.helpTitle': '需要 eSIM 帮助？', 'orders.helpDescription': '我们的支持团队全天候协助处理 eSIM 激活、流量使用或技术问题。', 'orders.contactSupport': '联系支持', 'orders.viewFaq': '查看常见问题',
    'orderDetail.notFound': '未找到订单', 'orderDetail.notFoundDescription': '您查找的订单不存在。', 'orderDetail.backToOrders': '返回订单列表', 'orderDetail.activationProgress': 'eSIM 激活进度', 'orderDetail.orderPlaced': '已下单', 'orderDetail.paymentConfirmed': '付款已确认', 'orderDetail.provisioned': 'eSIM 已配置', 'orderDetail.qrSent': '二维码已发送', 'orderDetail.activated': '已激活', 'orderDetail.packages': 'eSIM 套餐', 'orderDetail.qty': '数量：{quantity}', 'orderDetail.each': '每件 ${amount}', 'orderDetail.subtotal': '小计', 'orderDetail.delivery': '交付', 'orderDetail.instantEmail': '即时（电子邮件）', 'orderDetail.total': '总计', 'orderDetail.quickActions': '快捷操作', 'orderDetail.viewQr': '显示二维码', 'orderDetail.cancelTitle': '取消订单', 'orderDetail.cancelDescription': '如果您不再需要此 eSIM，可以取消订单并获得全额退款。', 'orderDetail.cancel': '取消订单', 'orderDetail.backToEsims': '返回我的 eSIM',
    'orderSuccess.title': 'eSIM 订单已确认！', 'orderSuccess.subtitle': '您的 eSIM 套餐正在准备激活。', 'orderSuccess.orderNumber': '订单号', 'orderSuccess.paymentProcessed': '您的付款已成功处理', 'orderSuccess.emailSent': 'eSIM 二维码和激活说明已发送至您的邮箱', 'orderSuccess.scanQr': '使用设备扫描二维码以安装 eSIM 配置文件', 'orderSuccess.howToActivate': '如何激活 eSIM', 'orderSuccess.checkEmail': '检查邮箱', 'orderSuccess.checkEmailDescription': '您将在几分钟内收到包含 eSIM 二维码的邮件', 'orderSuccess.scanQrTitle': '扫描二维码', 'orderSuccess.scanQrDescription': '前往“设置 > 蜂窝网络 > 添加 eSIM”并扫描二维码', 'orderSuccess.activateDestination': '抵达目的地后激活', 'orderSuccess.activateDestinationDescription': '抵达后开启数据漫游，eSIM 将自动连接', 'orderSuccess.viewEsims': '查看我的 eSIM', 'orderSuccess.browsePackages': '浏览更多套餐',
    'orderCancelled.title': '付款已取消', 'orderCancelled.subtitle': '您的付款已取消，账户未产生任何扣款。', 'orderCancelled.cartSaved': '购物车内容已保留', 'orderCancelled.cartSavedDescription': '所有 eSIM 套餐仍在购物车中，您可以随时完成购买', 'orderCancelled.needHelp': '需要帮助？', 'orderCancelled.needHelpDescription': '如果结算过程中遇到问题，我们的支持团队全天候为您服务', 'orderCancelled.whatHappened': '发生了什么？', 'orderCancelled.whatHappenedDescription': '您在完成 eSIM 订单前取消了付款流程，可能原因包括：', 'orderCancelled.reasonBack': '在结算过程中点击了返回按钮', 'orderCancelled.reasonClosed': '关闭了付款窗口', 'orderCancelled.reasonReview': '决定重新查看 eSIM 选择', 'orderCancelled.reasonIssue': '遇到技术问题', 'orderCancelled.returnCart': '返回购物车', 'orderCancelled.browsePackages': '浏览套餐', 'orderCancelled.assistance': '需要协助？', 'orderCancelled.contactSupport': '联系支持',
    'checkout.home': '首页', 'checkout.packages': 'eSIM 套餐', 'checkout.title': '结算', 'checkout.account': '账户信息', 'checkout.device': '设备信息', 'checkout.traveler': '旅行者信息', 'checkout.payment': '支付方式', 'checkout.summary': '订单摘要',
    'checkout.loginPrompt': '已有账户？', 'checkout.login': '登录', 'checkout.email': '电子邮箱', 'checkout.emailDelivery': '您的 eSIM 将发送到此电子邮箱', 'checkout.deviceType': '设备类型', 'checkout.selectDevice': '选择设备类型', 'checkout.iphone': 'iPhone（XR 或更新型号）', 'checkout.samsung': 'Samsung Galaxy（S20 或更新型号）', 'checkout.pixel': 'Google Pixel（3 或更新型号）', 'checkout.ipad': 'iPad（第 7 代或更新型号）', 'checkout.otherDevice': '其他兼容 eSIM 的设备', 'checkout.osVersion': 'iOS / Android 版本', 'checkout.compatibility': '请确认您的设备支持 eSIM。大多数现代智能手机都支持 eSIM 技术。', 'checkout.checkCompatibility': '检查设备兼容性', 'checkout.firstName': '名', 'checkout.lastName': '姓', 'checkout.phone': '电话号码', 'checkout.travelDate': '出行日期', 'checkout.card': '信用卡/借记卡', 'checkout.cardNumber': '卡号', 'checkout.expiry': '有效期', 'checkout.cvc': 'CVC/CVV', 'checkout.saveCard': '保存此卡以便下次购买', 'checkout.agree': '我同意', 'checkout.and': '和', 'checkout.subtotal': '小计', 'checkout.tax': '税费', 'checkout.discount': '折扣', 'checkout.total': '总计', 'checkout.promo': '优惠码', 'checkout.enterCode': '输入优惠码', 'checkout.apply': '应用', 'checkout.processing': '处理中...', 'checkout.complete': '完成购买', 'checkout.deliveryNote': '购买后您将立即通过电子邮箱收到 eSIM', 'checkout.error.emailRequired': '请输入电子邮箱', 'checkout.error.emailFormat': '电子邮箱格式无效', 'checkout.error.firstName': '请输入名', 'checkout.error.lastName': '请输入姓', 'checkout.error.address': '请输入地址', 'checkout.error.city': '请输入城市', 'checkout.error.state': '请输入州/省', 'checkout.error.postal': '请输入邮政编码', 'checkout.error.country': '请选择国家/地区', 'checkout.error.phone': '请输入电话号码',
    'product.notFound': '未找到商品', 'product.notFoundDescription': '您查找的 eSIM 套餐不存在。', 'product.features': '主要功能', 'product.description': '商品描述', 'product.reviews': '客户评价', 'product.choosePlan': '选择套餐', 'product.quantity': '数量', 'product.needHelp': '需要帮助？',
    'product.goBack': '返回', 'product.new': '新品', 'product.reviewsCount': '{count} 条评价', 'product.data': '流量', 'product.validity': '有效期', 'product.network': '网络', 'product.coverage': '4G/5G 覆盖', 'product.defaultData': '5GB 高速流量', 'product.defaultValidity': '30 天', 'product.descriptionBody': '无论您身在何处，都能通过我们的高级 eSIM 服务保持连接。享受高速流量、轻松设置以及覆盖各大网络的稳定连接。', 'product.basedOn': '基于 {count} 条评价', 'product.star': '星', 'product.stars': '星', 'product.seeAll': '查看全部 {count} 条评价', 'product.outOfStock': '缺货', 'product.inStock': '有货', 'product.taxesIncluded': '含税', 'product.buyNow': '立即购买', 'product.addToCart': '加入购物车', 'product.secure': '安全交易', 'product.instantDelivery': '通过电子邮箱即时交付', 'product.refund': '未激活可享 7 天退款保障', 'product.supportBody': '我们的支持团队全天候为您解答问题。', 'product.chatSupport': '联系支持', 'product.alsoLike': '您可能还喜欢', 'product.bestSeller': '畅销商品', 'product.viewDetails': '查看详情',
    'travelpass.cart.title': '购物车', 'travelpass.cart.empty': '购物车为空', 'travelpass.cart.emptyDescription': '浏览我们的 eSIM 套餐开始使用', 'travelpass.cart.continueShopping': '继续购物', 'travelpass.cart.orderSummary': '订单摘要', 'travelpass.cart.total': '总计', 'travelpass.cart.checkout': '前往结算',
    'travelpass.help.title': '帮助中心', 'travelpass.help.subtitle': '查找有关 eSIM 激活、流量使用等常见问题的答案',
    'travelpass.contact.title': 'eSIM 支持', 'travelpass.contact.subtitle': '我们的团队全天候帮助处理激活、连接或账单问题',
    'legal.privacy.title': '隐私政策', 'legal.terms.title': '服务条款', 'legal.lastUpdated': '最后更新：{date}',
    'appDownload.mobile.download': '下载',
    'appDownload.hero.eyebrow': '适用于 Android 的 EasyEUICC',
    'appDownload.hero.title': '下载 EasyEUICC',
    'appDownload.hero.noAds': '无广告',
    'appDownload.hero.profileManagement': 'eUICC 管理',
    'appDownload.hero.directInstall': 'APK 直接安装',
    'appDownload.download.scan': '扫码或点击下载最新 APK',
    'appDownload.download.currentVersion': '当前版本 {version}。',
    'appDownload.download.androidRecommendation': '建议使用 Android 9 及以上版本。下载后请核对签名和校验信息。',
    'appDownload.tools.title': '配置文件工具',
    'appDownload.tools.ready': '就绪',
    'appDownload.tools.scan.title': '扫描激活码',
    'appDownload.tools.scan.meta': '相机扫描或手动输入',
    'appDownload.tools.switch.title': '切换当前配置文件',
    'appDownload.tools.switch.meta': '快速控制配置文件',
    'appDownload.tools.storage.title': '本地配置文件存储',
    'appDownload.tools.storage.meta': '以设备为中心管理',
    'appDownload.tools.latestPackage': '最新安装包',
    'appDownload.features.manage.title': '配置文件管理',
    'appDownload.features.manage.body': '查看、启用和维护设备中的 eSIM 配置文件。',
    'appDownload.features.scan.title': '扫码添加',
    'appDownload.features.scan.body': '通过二维码或手动输入快速添加激活信息。',
    'appDownload.features.local.title': '本地优先',
    'appDownload.features.local.body': '核心管理操作在设备侧完成，减少不必要的依赖。',
    'appDownload.features.control.title': '自主可控',
    'appDownload.features.control.body': '关键操作保留在设备端，减少对外部服务的依赖。',
    'appDownload.security.eyebrow': '安全下载',
    'appDownload.security.title': '只提供已确认的最新 Android 安装包。',
    'appDownload.security.version': '版本号：{version}',
    'appDownload.security.package': '包名：im.angry.easyeuicc',
    'appDownload.security.targetSdk': 'Target SDK：35',
  },
  'zh-Hant': {
    'common.privacy': '隱私政策',
    'common.terms': '服務條款',
    'common.downloadApk': '下載 APK',
    'auth.login.subtitle': '登入您的帳戶', 'auth.register.subtitle': '建立您的帳戶', 'auth.email': '電子郵件', 'auth.password': '密碼', 'auth.firstName': '名字', 'auth.lastName': '姓氏', 'auth.confirmPassword': '確認密碼', 'auth.passwordMismatch': '兩次輸入的密碼不一致', 'auth.signIn': '登入', 'auth.signUp': '註冊', 'auth.createAccount': '建立帳戶', 'auth.forgotPassword': '忘記密碼？', 'auth.orContinue': '或使用以下方式繼續', 'auth.orSignUp': '或使用以下方式註冊', 'auth.google': '使用 Google 繼續', 'auth.hidePassword': '隱藏密碼', 'auth.showPassword': '顯示密碼',
    'nav.features': '功能', 'nav.security': '安全', 'nav.download': '下載',
    'orders.placedOn': '下單時間：', 'orders.buyNew': '購買新 eSIM', 'orders.active': '進行中', 'orders.upcoming': '即將開始', 'orders.expired': '已結束', 'orders.all': '全部', 'orders.errorTitle': '發生錯誤', 'orders.home': '首頁', 'orders.account': '我的帳戶', 'orders.emptyTitle': '找不到 eSIM', 'orders.emptyDescription': '此分類下暫時沒有 eSIM。', 'orders.browsePackages': '瀏覽套餐', 'orders.ordered': '下單時間：', 'orders.status': '狀態：', 'orders.dataUsage': '流量使用', 'orders.daysRemaining': '剩餘 {days} 天', 'orders.topUp': '儲值流量', 'orders.showQr': '顯示 QR code', 'orders.speed': '網速', 'orders.highSpeed': '4G/5G 高速', 'orders.network': '網路', 'orders.majorCarriers': '主要電信商', 'orders.support': '支援', 'orders.available247': '全天候可用', 'orders.manageSettings': '管理設定', 'orders.deviceInstructions': '裝置說明', 'orders.getSupport': '取得支援', 'orders.viewReceipt': '檢視收據', 'orders.prev': '上一頁', 'orders.next': '下一頁', 'orders.helpTitle': '需要 eSIM 協助？', 'orders.helpDescription': '我們的支援團隊全天候協助處理 eSIM 啟用、流量使用或技術問題。', 'orders.contactSupport': '聯絡支援', 'orders.viewFaq': '檢視常見問題',
    'orderDetail.notFound': '找不到訂單', 'orderDetail.notFoundDescription': '您查找的訂單不存在。', 'orderDetail.backToOrders': '返回訂單列表', 'orderDetail.activationProgress': 'eSIM 啟用進度', 'orderDetail.orderPlaced': '已下單', 'orderDetail.paymentConfirmed': '付款已確認', 'orderDetail.provisioned': 'eSIM 已設定', 'orderDetail.qrSent': 'QR code 已傳送', 'orderDetail.activated': '已啟用', 'orderDetail.packages': 'eSIM 套餐', 'orderDetail.qty': '數量：{quantity}', 'orderDetail.each': '每件 ${amount}', 'orderDetail.subtotal': '小計', 'orderDetail.delivery': '交付', 'orderDetail.instantEmail': '即時（電子郵件）', 'orderDetail.total': '總計', 'orderDetail.quickActions': '快速操作', 'orderDetail.viewQr': '顯示 QR code', 'orderDetail.cancelTitle': '取消訂單', 'orderDetail.cancelDescription': '如果您不再需要此 eSIM，可以取消訂單並獲得全額退款。', 'orderDetail.cancel': '取消訂單', 'orderDetail.backToEsims': '返回我的 eSIM',
    'orderSuccess.title': 'eSIM 訂單已確認！', 'orderSuccess.subtitle': '您的 eSIM 套餐正在準備啟用。', 'orderSuccess.orderNumber': '訂單編號', 'orderSuccess.paymentProcessed': '您的付款已成功處理', 'orderSuccess.emailSent': 'eSIM QR code 與啟用說明已寄送至您的電子郵件', 'orderSuccess.scanQr': '使用裝置掃描 QR code 以安裝 eSIM 設定檔', 'orderSuccess.howToActivate': '如何啟用 eSIM', 'orderSuccess.checkEmail': '檢查電子郵件', 'orderSuccess.checkEmailDescription': '您將在幾分鐘內收到包含 eSIM QR code 的電子郵件', 'orderSuccess.scanQrTitle': '掃描 QR code', 'orderSuccess.scanQrDescription': '前往「設定 > 行動服務 > 加入 eSIM」並掃描 QR code', 'orderSuccess.activateDestination': '抵達目的地後啟用', 'orderSuccess.activateDestinationDescription': '抵達後開啟數據漫遊，eSIM 將自動連線', 'orderSuccess.viewEsims': '檢視我的 eSIM', 'orderSuccess.browsePackages': '瀏覽更多套餐',
    'orderCancelled.title': '付款已取消', 'orderCancelled.subtitle': '您的付款已取消，帳戶未產生任何扣款。', 'orderCancelled.cartSaved': '購物車內容已保留', 'orderCancelled.cartSavedDescription': '所有 eSIM 套餐仍在購物車中，您可以隨時完成購買', 'orderCancelled.needHelp': '需要協助？', 'orderCancelled.needHelpDescription': '如果結帳過程中遇到問題，我們的支援團隊全天候為您服務', 'orderCancelled.whatHappened': '發生了什麼？', 'orderCancelled.whatHappenedDescription': '您在完成 eSIM 訂單前取消了付款流程，可能原因包括：', 'orderCancelled.reasonBack': '在結帳過程中點擊了返回按鈕', 'orderCancelled.reasonClosed': '關閉了付款視窗', 'orderCancelled.reasonReview': '決定重新檢視 eSIM 選擇', 'orderCancelled.reasonIssue': '遇到技術問題', 'orderCancelled.returnCart': '返回購物車', 'orderCancelled.browsePackages': '瀏覽套餐', 'orderCancelled.assistance': '需要協助？', 'orderCancelled.contactSupport': '聯絡支援',
    'checkout.home': '首頁', 'checkout.packages': 'eSIM 套餐', 'checkout.title': '結帳', 'checkout.account': '帳戶資訊', 'checkout.device': '裝置資訊', 'checkout.traveler': '旅客資訊', 'checkout.payment': '付款方式', 'checkout.summary': '訂單摘要',
    'checkout.loginPrompt': '已有帳戶？', 'checkout.login': '登入', 'checkout.email': '電子郵件', 'checkout.emailDelivery': '您的 eSIM 將寄送至此電子郵件', 'checkout.deviceType': '裝置類型', 'checkout.selectDevice': '選擇裝置類型', 'checkout.iphone': 'iPhone（XR 或更新型號）', 'checkout.samsung': 'Samsung Galaxy（S20 或更新型號）', 'checkout.pixel': 'Google Pixel（3 或更新型號）', 'checkout.ipad': 'iPad（第 7 代或更新型號）', 'checkout.otherDevice': '其他相容 eSIM 的裝置', 'checkout.osVersion': 'iOS / Android 版本', 'checkout.compatibility': '請確認您的裝置支援 eSIM。大多數現代智慧型手機都支援 eSIM 技術。', 'checkout.checkCompatibility': '檢查裝置相容性', 'checkout.firstName': '名字', 'checkout.lastName': '姓氏', 'checkout.phone': '電話號碼', 'checkout.travelDate': '旅遊日期', 'checkout.card': '信用卡/簽帳金融卡', 'checkout.cardNumber': '卡號', 'checkout.expiry': '有效期限', 'checkout.cvc': 'CVC/CVV', 'checkout.saveCard': '儲存此卡以便下次購買', 'checkout.agree': '我同意', 'checkout.and': '和', 'checkout.subtotal': '小計', 'checkout.tax': '稅金', 'checkout.discount': '折扣', 'checkout.total': '總計', 'checkout.promo': '優惠碼', 'checkout.enterCode': '輸入優惠碼', 'checkout.apply': '套用', 'checkout.processing': '處理中...', 'checkout.complete': '完成購買', 'checkout.deliveryNote': '購買後您將立即透過電子郵件收到 eSIM', 'checkout.error.emailRequired': '請輸入電子郵件', 'checkout.error.emailFormat': '電子郵件格式無效', 'checkout.error.firstName': '請輸入名字', 'checkout.error.lastName': '請輸入姓氏', 'checkout.error.address': '請輸入地址', 'checkout.error.city': '請輸入城市', 'checkout.error.state': '請輸入州/省', 'checkout.error.postal': '請輸入郵遞區號', 'checkout.error.country': '請選擇國家/地區', 'checkout.error.phone': '請輸入電話號碼',
    'product.notFound': '找不到商品', 'product.notFoundDescription': '您查找的 eSIM 套餐不存在。', 'product.features': '主要功能', 'product.description': '商品描述', 'product.reviews': '客戶評價', 'product.choosePlan': '選擇套餐', 'product.quantity': '數量', 'product.needHelp': '需要協助？',
    'product.goBack': '返回', 'product.new': '新品', 'product.reviewsCount': '{count} 則評價', 'product.data': '流量', 'product.validity': '有效期', 'product.network': '網路', 'product.coverage': '4G/5G 覆蓋', 'product.defaultData': '5GB 高速流量', 'product.defaultValidity': '30 天', 'product.descriptionBody': '無論身在何處，都能透過我們的高級 eSIM 服務保持連線。享受高速流量、輕鬆設定以及涵蓋各大網路的穩定連線。', 'product.basedOn': '根據 {count} 則評價', 'product.star': '顆星', 'product.stars': '顆星', 'product.seeAll': '查看全部 {count} 則評價', 'product.outOfStock': '缺貨', 'product.inStock': '有貨', 'product.taxesIncluded': '含稅', 'product.buyNow': '立即購買', 'product.addToCart': '加入購物車', 'product.secure': '安全交易', 'product.instantDelivery': '透過電子郵件即時交付', 'product.refund': '未啟用可享 7 天退款保障', 'product.supportBody': '我們的支援團隊全天候為您解答問題。', 'product.chatSupport': '聯絡支援', 'product.alsoLike': '您可能也喜歡', 'product.bestSeller': '熱賣商品', 'product.viewDetails': '查看詳情',
    'travelpass.cart.title': '購物車', 'travelpass.cart.empty': '購物車是空的', 'travelpass.cart.emptyDescription': '瀏覽我們的 eSIM 套餐開始使用', 'travelpass.cart.continueShopping': '繼續購物', 'travelpass.cart.orderSummary': '訂單摘要', 'travelpass.cart.total': '總計', 'travelpass.cart.checkout': '前往結帳',
    'travelpass.help.title': '說明中心', 'travelpass.help.subtitle': '查找有關 eSIM 啟用、流量使用等常見問題的答案',
    'travelpass.contact.title': 'eSIM 支援', 'travelpass.contact.subtitle': '我們的團隊全天候協助處理啟用、連線或帳單問題',
    'legal.privacy.title': '隱私政策', 'legal.terms.title': '服務條款', 'legal.lastUpdated': '最後更新：{date}',
    'appDownload.mobile.download': '下載',
    'appDownload.hero.eyebrow': '適用於 Android 的 EasyEUICC',
    'appDownload.hero.title': '下載 EasyEUICC',
    'appDownload.hero.noAds': '無廣告',
    'appDownload.hero.profileManagement': 'eUICC 管理',
    'appDownload.hero.directInstall': 'APK 直接安裝',
    'appDownload.download.scan': '掃描或點擊下載最新 APK',
    'appDownload.download.currentVersion': '目前版本 {version}。',
    'appDownload.download.androidRecommendation': '建議使用 Android 9 或以上版本。下載後請核對簽名與校驗資訊。',
    'appDownload.tools.title': '設定檔工具',
    'appDownload.tools.ready': '就緒',
    'appDownload.tools.scan.title': '掃描啟用碼',
    'appDownload.tools.scan.meta': '相機掃描或手動輸入',
    'appDownload.tools.switch.title': '切換目前設定檔',
    'appDownload.tools.switch.meta': '快速控制設定檔',
    'appDownload.tools.storage.title': '本機設定檔儲存',
    'appDownload.tools.storage.meta': '以裝置為中心管理',
    'appDownload.tools.latestPackage': '最新安裝包',
    'appDownload.features.manage.title': '設定檔管理',
    'appDownload.features.manage.body': '查看、啟用與維護裝置中的 eSIM 設定檔。',
    'appDownload.features.scan.title': '掃描新增',
    'appDownload.features.scan.body': '透過 QR code 或手動輸入快速加入啟用資訊。',
    'appDownload.features.local.title': '本機優先',
    'appDownload.features.local.body': '核心管理操作在裝置端完成，減少不必要的依賴。',
    'appDownload.features.control.title': '自主掌控',
    'appDownload.features.control.body': '關鍵操作保留在裝置端，減少對外部服務的依賴。',
    'appDownload.security.eyebrow': '安全下載',
    'appDownload.security.title': '只提供已確認的最新 Android 安裝包。',
    'appDownload.security.version': '版本號：{version}',
    'appDownload.security.package': '套件名稱：im.angry.easyeuicc',
    'appDownload.security.targetSdk': 'Target SDK：35',
  },
};

Object.assign(themeMessages.en, {
  'account.signInRequired': 'Sign In Required', 'account.signInSettings': 'Please sign in to access settings.', 'account.signInAccount': 'Please sign in to access your account.', 'account.signIn': 'Sign In', 'account.home': 'Home', 'account.title': 'My Account', 'account.welcome': 'Welcome back, {name}!', 'account.logout': 'Log Out', 'account.dashboard': 'Dashboard', 'account.profile': 'My Profile', 'account.esims': 'My eSIMs', 'account.orders': 'Order History', 'account.payments': 'Payment Methods', 'account.devices': 'My Devices', 'account.settings': 'Account Settings', 'account.support': 'Support', 'account.activeEsims': 'Active eSIMs', 'account.viewActive': 'View active eSIMs', 'account.dataRemaining': 'Data Remaining', 'account.validDays': 'Valid for {days} more days', 'account.recentOrders': 'Recent Orders', 'account.viewHistory': 'View order history', 'account.quickActions': 'Quick Actions', 'account.manage': 'Manage', 'account.viewAll': 'View All', 'account.orderId': 'Order ID', 'account.date': 'Date', 'account.product': 'Product', 'account.amount': 'Amount', 'account.status': 'Status', 'account.actions': 'Actions', 'account.savedPayments': 'Saved Payment Methods', 'account.addCard': 'Add New Card', 'account.expires': 'Expires {value}', 'account.dataUsage': 'Data Usage', 'account.settingsTitle': 'Account Settings', 'account.settingsSubtitle': 'Manage your profile and account preferences', 'account.back': 'Back', 'account.profileInfo': 'Profile Information', 'account.profileSaved': 'Profile saved successfully!', 'account.fullName': 'Full Name', 'account.fullNamePlaceholder': 'Your full name', 'account.phone': 'Phone Number', 'account.dob': 'Date of Birth', 'account.gender': 'Gender', 'account.preferNot': 'Prefer not to say', 'account.male': 'Male', 'account.female': 'Female', 'account.other': 'Other', 'account.language': 'Language', 'account.timezone': 'Timezone', 'account.save': 'Save Changes', 'account.saving': 'Saving...', 'account.changePassword': 'Change Password', 'account.passwordChanged': 'Password changed successfully!', 'account.currentPassword': 'Current Password', 'account.currentPasswordPlaceholder': 'Enter current password', 'account.newPassword': 'New Password', 'account.newPasswordPlaceholder': 'Enter new password', 'account.confirmNewPassword': 'Confirm New Password', 'account.confirmNewPasswordPlaceholder': 'Confirm new password', 'account.passwordMismatch': 'Passwords do not match', 'account.changing': 'Changing...',
  'travelpass.search.title': 'Search eSIM Packages', 'travelpass.search.resultsFor': 'Results for "{query}"', 'travelpass.search.filters': 'Filters', 'travelpass.search.region': 'Region', 'travelpass.search.allRegions': 'All Regions', 'travelpass.search.allPrices': 'All Prices', 'travelpass.search.noResults': 'No Results Found', 'travelpass.search.tryAdjusting': 'Try adjusting your search or filter criteria', 'travelpass.sort.mostPopular': 'Most Popular', 'travelpass.sort.newest': 'Newest First', 'travelpass.sort.priceLow': 'Price: Low to High', 'travelpass.sort.priceHigh': 'Price: High to Low', 'travelpass.sort.name': 'Name', 'travelpass.sort.relevance': 'Most Relevant', 'travelpass.sort.rating': 'Top Rated', 'travelpass.badge.sale': 'SALE', 'travelpass.badge.new': 'NEW', 'travelpass.feature.highSpeed': 'High-speed data', 'travelpass.feature.duration': 'Flexible duration', 'travelpass.feature.coverage': 'Wide coverage', 'travelpass.bestsellers.empty': 'No bestsellers available', 'travelpass.newArrivals.empty': 'No new arrivals yet', 'travelpass.products.searchPlaceholder': 'Search destination', 'travelpass.products.refine': 'Refine', 'travelpass.products.noPlans': 'No plans found', 'travelpass.products.noPlansHint': 'Try a broader destination or fewer filters.', 'travelpass.products.featured': 'Featured plan', 'travelpass.products.popularDestinations': 'Popular destinations', 'travelpass.products.seeAll': 'See all'
});
Object.assign(themeMessages['zh-Hans'], {
  'account.signInRequired': '需要登录', 'account.signInSettings': '请登录后访问设置。', 'account.signInAccount': '请登录后访问您的账户。', 'account.signIn': '登录', 'account.home': '首页', 'account.title': '我的账户', 'account.welcome': '欢迎回来，{name}！', 'account.logout': '退出登录', 'account.dashboard': '仪表盘', 'account.profile': '我的资料', 'account.esims': '我的 eSIM', 'account.orders': '订单历史', 'account.payments': '支付方式', 'account.devices': '我的设备', 'account.settings': '账户设置', 'account.support': '支持', 'account.activeEsims': '已启用的 eSIM', 'account.viewActive': '查看已启用 eSIM', 'account.dataRemaining': '剩余流量', 'account.validDays': '还可使用 {days} 天', 'account.recentOrders': '最近订单', 'account.viewHistory': '查看订单历史', 'account.quickActions': '快捷操作', 'account.manage': '管理', 'account.viewAll': '查看全部', 'account.orderId': '订单号', 'account.date': '日期', 'account.product': '商品', 'account.amount': '金额', 'account.status': '状态', 'account.actions': '操作', 'account.savedPayments': '已保存的支付方式', 'account.addCard': '添加新卡', 'account.expires': '{value} 到期', 'account.dataUsage': '流量使用情况', 'account.settingsTitle': '账户设置', 'account.settingsSubtitle': '管理您的资料和账户偏好', 'account.back': '返回', 'account.profileInfo': '个人资料', 'account.profileSaved': '资料保存成功！', 'account.fullName': '姓名', 'account.fullNamePlaceholder': '请输入姓名', 'account.phone': '电话号码', 'account.dob': '出生日期', 'account.gender': '性别', 'account.preferNot': '不愿透露', 'account.male': '男', 'account.female': '女', 'account.other': '其他', 'account.language': '语言', 'account.timezone': '时区', 'account.save': '保存更改', 'account.saving': '保存中...', 'account.changePassword': '修改密码', 'account.passwordChanged': '密码修改成功！', 'account.currentPassword': '当前密码', 'account.currentPasswordPlaceholder': '请输入当前密码', 'account.newPassword': '新密码', 'account.newPasswordPlaceholder': '请输入新密码', 'account.confirmNewPassword': '请再次输入新密码', 'account.confirmNewPasswordPlaceholder': '请再次输入新密码', 'account.passwordMismatch': '两次输入的密码不一致', 'account.changing': '修改中...',
  'travelpass.search.title': '搜索 eSIM 套餐', 'travelpass.search.resultsFor': '“{query}”的搜索结果', 'travelpass.search.filters': '筛选', 'travelpass.search.region': '地区', 'travelpass.search.allRegions': '所有地区', 'travelpass.search.allPrices': '所有价格', 'travelpass.search.noResults': '未找到结果', 'travelpass.search.tryAdjusting': '请调整搜索词或筛选条件', 'travelpass.sort.mostPopular': '最受欢迎', 'travelpass.sort.newest': '最新上架', 'travelpass.sort.priceLow': '价格从低到高', 'travelpass.sort.priceHigh': '价格从高到低', 'travelpass.sort.name': '名称', 'travelpass.sort.relevance': '最相关', 'travelpass.sort.rating': '评分最高', 'travelpass.badge.sale': '促销', 'travelpass.badge.new': '新品', 'travelpass.feature.highSpeed': '高速流量', 'travelpass.feature.duration': '灵活期限', 'travelpass.feature.coverage': '广泛覆盖', 'travelpass.bestsellers.empty': '暂无畅销商品', 'travelpass.newArrivals.empty': '暂无新品', 'travelpass.products.searchPlaceholder': '搜索目的地', 'travelpass.products.refine': '筛选条件', 'travelpass.products.noPlans': '未找到套餐', 'travelpass.products.noPlansHint': '请尝试更广泛的目的地或减少筛选条件。', 'travelpass.products.featured': '精选套餐', 'travelpass.products.popularDestinations': '热门目的地', 'travelpass.products.seeAll': '查看全部'
});
Object.assign(themeMessages['zh-Hant'], {
  'account.signInRequired': '需要登入', 'account.signInSettings': '請登入後存取設定。', 'account.signInAccount': '請登入後存取您的帳戶。', 'account.signIn': '登入', 'account.home': '首頁', 'account.title': '我的帳戶', 'account.welcome': '歡迎回來，{name}！', 'account.logout': '登出', 'account.dashboard': '儀表板', 'account.profile': '我的資料', 'account.esims': '我的 eSIM', 'account.orders': '訂單記錄', 'account.payments': '付款方式', 'account.devices': '我的裝置', 'account.settings': '帳戶設定', 'account.support': '支援', 'account.activeEsims': '已啟用的 eSIM', 'account.viewActive': '查看已啟用 eSIM', 'account.dataRemaining': '剩餘流量', 'account.validDays': '還可使用 {days} 天', 'account.recentOrders': '最近訂單', 'account.viewHistory': '查看訂單記錄', 'account.quickActions': '快速操作', 'account.manage': '管理', 'account.viewAll': '查看全部', 'account.orderId': '訂單編號', 'account.date': '日期', 'account.product': '商品', 'account.amount': '金額', 'account.status': '狀態', 'account.actions': '操作', 'account.savedPayments': '已儲存的付款方式', 'account.addCard': '新增卡片', 'account.expires': '{value} 到期', 'account.dataUsage': '流量使用量', 'account.settingsTitle': '帳戶設定', 'account.settingsSubtitle': '管理您的資料與帳戶偏好', 'account.back': '返回', 'account.profileInfo': '個人資料', 'account.profileSaved': '資料儲存成功！', 'account.fullName': '姓名', 'account.fullNamePlaceholder': '請輸入姓名', 'account.phone': '電話號碼', 'account.dob': '出生日期', 'account.gender': '性別', 'account.preferNot': '不願透露', 'account.male': '男', 'account.female': '女', 'account.other': '其他', 'account.language': '語言', 'account.timezone': '時區', 'account.save': '儲存變更', 'account.saving': '儲存中...', 'account.changePassword': '變更密碼', 'account.passwordChanged': '密碼變更成功！', 'account.currentPassword': '目前密碼', 'account.currentPasswordPlaceholder': '請輸入目前密碼', 'account.newPassword': '新密碼', 'account.newPasswordPlaceholder': '請輸入新密碼', 'account.confirmNewPassword': '確認新密碼', 'account.confirmNewPasswordPlaceholder': '請再次輸入新密碼', 'account.passwordMismatch': '兩次輸入的密碼不一致', 'account.changing': '變更中...',
  'travelpass.search.title': '搜尋 eSIM 套餐', 'travelpass.search.resultsFor': '「{query}」的搜尋結果', 'travelpass.search.filters': '篩選', 'travelpass.search.region': '地區', 'travelpass.search.allRegions': '所有地區', 'travelpass.search.allPrices': '所有價格', 'travelpass.search.noResults': '找不到結果', 'travelpass.search.tryAdjusting': '請調整搜尋內容或篩選條件', 'travelpass.sort.mostPopular': '最受歡迎', 'travelpass.sort.newest': '最新上架', 'travelpass.sort.priceLow': '價格由低至高', 'travelpass.sort.priceHigh': '價格由高至低', 'travelpass.sort.name': '名稱', 'travelpass.sort.relevance': '最相關', 'travelpass.sort.rating': '評分最高', 'travelpass.badge.sale': '優惠', 'travelpass.badge.new': '新品', 'travelpass.feature.highSpeed': '高速流量', 'travelpass.feature.duration': '彈性期限', 'travelpass.feature.coverage': '廣泛覆蓋', 'travelpass.bestsellers.empty': '暫無暢銷商品', 'travelpass.newArrivals.empty': '暫無新品', 'travelpass.products.searchPlaceholder': '搜尋目的地', 'travelpass.products.refine': '篩選條件', 'travelpass.products.noPlans': '找不到套餐', 'travelpass.products.noPlansHint': '請嘗試更廣泛的目的地或減少篩選條件。', 'travelpass.products.featured': '精選套餐', 'travelpass.products.popularDestinations': '熱門目的地', 'travelpass.products.seeAll': '查看全部'
});

const legalEnglish = {
  'faq.dataUsage.q1': 'How fast is the data connection?', 'faq.dataUsage.a1': '4G/LTE and 5G speeds depend on your location and local carrier network.', 'faq.dataUsage.q2': 'Can I check my remaining data?', 'faq.dataUsage.a2': 'Open My eSIMs in your account to see real-time usage and balance.', 'faq.dataUsage.q3': 'What happens when my data runs out?', 'faq.dataUsage.a3': 'Top up anytime. Your connection pauses until more data is added or the plan renews.',
  'faq.billing.q1': 'What payment methods do you accept?', 'faq.billing.a1': 'We accept major cards, PayPal, Apple Pay, and Google Pay.', 'faq.billing.q2': 'Can I get a refund?', 'faq.billing.a2': 'Unactivated eSIMs qualify for a full refund within 7 days. Contact support for help.', 'faq.billing.q3': 'How do I get a receipt?', 'faq.billing.a3': 'Receipts are emailed automatically and available in My Account.',
  'faq.troubleshooting.q1': 'My eSIM is not connecting', 'faq.troubleshooting.a1': 'Enable data roaming, set the eSIM as your data line, and toggle airplane mode.', 'faq.troubleshooting.q2': 'The QR code is not scanning', 'faq.troubleshooting.a2': 'Scan a clear code displayed on another device or contact support.', 'faq.troubleshooting.q3': 'Can I use my eSIM on multiple devices?', 'faq.troubleshooting.a3': 'No. Each profile is tied to one device; contact support to transfer it.',
  'legal.privacy.information-collect.title': 'Information We Collect', 'legal.privacy.information-collect.content': 'We collect information you provide directly to us, such as your name, email, payment information, and device details needed for eSIM provisioning.', 'legal.privacy.how-we-use.title': 'How We Use Your Information', 'legal.privacy.how-we-use.content': 'We use collected information to provide and improve eSIM services, process transactions, deliver QR codes, and communicate about your account.', 'legal.privacy.information-sharing.title': 'Information Sharing', 'legal.privacy.information-sharing.content': 'We do not sell your personal information. Data may be shared with carrier partners solely for eSIM provisioning and activation.', 'legal.privacy.data-security.title': 'Data Security', 'legal.privacy.data-security.content': 'We use encryption, secure servers, and access controls to protect your personal information.', 'legal.privacy.your-rights.title': 'Your Rights', 'legal.privacy.your-rights.content': 'You may access, update, or delete your personal information and opt out of certain communications.', 'legal.privacy.contact.title': 'Contact Us', 'legal.privacy.contact.content': 'Questions about this policy? Contact privacy@travelpass.com or our 24/7 support chat.', 'legal.privacy.cookies.title': 'Cookies and Tracking Technologies', 'legal.privacy.cookies.content': 'We use cookies and similar technologies to understand activity on our website. You can control cookies in your browser.', 'legal.privacy.links.title': 'Third-Party Links', 'legal.privacy.links.content': 'Our website may contain third-party links. We are not responsible for external sites privacy practices.', 'legal.privacy.children.title': "Children's Privacy", 'legal.privacy.children.content': 'Our website is not intended for children under 13, and we do not knowingly collect their personal information.', 'legal.privacy.changes.title': 'Changes to This Privacy Policy', 'legal.privacy.changes.content': 'We may update this policy to reflect changes in our practices or legal requirements.',
  'legal.terms.acceptance.title': 'Acceptance of Terms', 'legal.terms.acceptance.content': 'By using TravelPass eSIM services, you agree to these terms. If you do not agree, do not use the service.', 'legal.terms.use-license.title': 'Use License', 'legal.terms.use-license.content': 'eSIM profiles are licensed for personal use only and may not be resold or shared. Each profile is tied to one device.', 'legal.terms.disclaimer.title': 'Disclaimer', 'legal.terms.disclaimer.content': 'Services are provided as is. Coverage, speeds, and availability depend on local carrier infrastructure.', 'legal.terms.limitations.title': 'Limitations', 'legal.terms.limitations.content': 'TravelPass and carrier partners are not liable for damages arising from use or inability to use eSIM services.', 'legal.terms.accuracy.title': 'Accuracy of Materials', 'legal.terms.accuracy.content': 'Package details may change due to carrier-level modifications; we strive to keep listings accurate.', 'legal.terms.refunds.title': 'Refund Policy', 'legal.terms.refunds.content': 'Unused, unactivated eSIMs qualify for a full refund within 7 days. Activated eSIM refunds are reviewed case by case.', 'legal.terms.modifications.title': 'Modifications to Terms', 'legal.terms.modifications.content': 'TravelPass may revise these terms at any time without notice.', 'legal.terms.law.title': 'Governing Law', 'legal.terms.law.content': 'These terms are governed by the laws of the jurisdiction in which TravelPass operates.', 'legal.terms.responsibilities.title': 'User Responsibilities', 'legal.terms.responsibilities.content': 'Do not use eSIM services unlawfully or in ways that could impair carrier networks.',
  'travelpass.search.priceRange': 'Price Range', 'travelpass.search.under10': 'Under $10', 'travelpass.search.10to25': '$10 - $25', 'travelpass.search.25to50': '$25 - $50', 'travelpass.search.over50': '$50+', 'travelpass.search.availableNow': 'Available Now', 'travelpass.search.clearFilters': 'Clear All Filters', 'travelpass.search.asia': 'Asia', 'travelpass.search.europe': 'Europe', 'travelpass.search.americas': 'Americas', 'travelpass.search.africa': 'Africa', 'travelpass.search.oceania': 'Oceania',
  'checkout.product': 'Japan 5GB eSIM', 'footer.copyright': 'Copyright {year} {brand}. All rights reserved.', 'footer.poweredBy': 'Powered by Jiffoo',
  'account.timezoneUtc': 'UTC', 'account.timezoneEastern': 'Eastern Time', 'account.timezoneCentral': 'Central Time', 'account.timezoneMountain': 'Mountain Time', 'account.timezonePacific': 'Pacific Time', 'account.timezoneJapan': 'Japan Standard Time', 'account.timezoneChina': 'China Standard Time', 'account.timezoneGmt': 'GMT', 'account.timezoneCET': 'Central European Time', 'checkout.paypal': 'PayPal', 'checkout.applePay': 'Apple Pay', 'travelpass.search.mostRelevant': 'Most Relevant', 'travelpass.search.priceLow': 'Price: Low to High', 'travelpass.search.name': 'Name', 'travelpass.search.topRated': 'Top Rated',
} as const;
Object.assign(themeMessages.en, legalEnglish);
Object.assign(themeMessages['zh-Hans'], { ...legalEnglish, 'faq.dataUsage.q1': '数据连接速度如何？', 'faq.dataUsage.a1': '4G/LTE 和 5G 速度取决于您所在位置及当地运营商网络。', 'faq.dataUsage.q2': '可以查看剩余流量吗？', 'faq.dataUsage.a2': '打开账户中的“我的 eSIM”即可查看实时用量和余额。', 'faq.dataUsage.q3': '流量用完后会怎样？', 'faq.dataUsage.a3': '可随时充值；在增加流量或套餐续期前，连接会暂停。', 'faq.billing.q1': '支持哪些付款方式？', 'faq.billing.a1': '支持主流银行卡、PayPal、Apple Pay 和 Google Pay。', 'faq.billing.q2': '可以退款吗？', 'faq.billing.a2': '未激活的 eSIM 可在 7 天内全额退款，请联系支持。', 'faq.billing.q3': '如何获取收据？', 'faq.billing.a3': '收据会自动发送到邮箱，也可在我的账户中查看。', 'faq.troubleshooting.q1': '我的 eSIM 无法连接', 'faq.troubleshooting.a1': '请开启数据漫游，将 eSIM 设为数据线路，并切换一次飞行模式。', 'faq.troubleshooting.q2': '二维码无法扫描', 'faq.troubleshooting.a2': '请在另一台设备上显示清晰二维码进行扫描，或联系支持。', 'faq.troubleshooting.q3': '可以在多台设备上使用 eSIM 吗？', 'faq.troubleshooting.a3': '不可以。每个配置文件绑定一台设备，如需转移请联系支持。', ...Object.fromEntries(Object.entries(legalEnglish).map(([k,v]) => [k, v])),'travelpass.search.priceRange':'价格范围','travelpass.search.under10':'低于 10 美元','travelpass.search.10to25':'10 - 25 美元','travelpass.search.25to50':'25 - 50 美元','travelpass.search.over50':'50 美元以上','travelpass.search.availableNow':'现货可用','travelpass.search.clearFilters':'清除全部筛选','travelpass.search.asia':'亚洲','travelpass.search.europe':'欧洲','travelpass.search.americas':'美洲','travelpass.search.africa':'非洲','travelpass.search.oceania':'大洋洲','footer.poweredBy':'由 Jiffoo 提供支持','account.timezoneEastern':'美国东部时间','account.timezoneCentral':'美国中部时间','account.timezoneMountain':'美国山区时间','account.timezonePacific':'美国太平洋时间','account.timezoneJapan':'日本标准时间','account.timezoneChina':'中国标准时间','account.timezoneCET':'欧洲中部时间','account.timezoneGmt':'格林尼治时间','footer.copyright':'版权所有 © {year} {brand}。保留所有权利。' });
Object.assign(themeMessages['zh-Hant'], { ...legalEnglish, 'faq.dataUsage.q1': '數據連線速度如何？', 'faq.dataUsage.a1': '4G/LTE 及 5G 速度取決於您所在位置及當地電訊商網絡。', 'faq.dataUsage.q2': '可以查看剩餘流量嗎？', 'faq.dataUsage.a2': '開啟帳戶中的「我的 eSIM」即可查看即時用量及餘額。', 'faq.dataUsage.q3': '流量用完後會怎樣？', 'faq.dataUsage.a3': '可隨時充值；在增加流量或方案續期前，連線會暫停。', 'travelpass.search.priceRange':'價格範圍','travelpass.search.under10':'低於 10 美元','travelpass.search.10to25':'10 - 25 美元','travelpass.search.25to50':'25 - 50 美元','travelpass.search.over50':'50 美元以上','travelpass.search.availableNow':'現有供應','travelpass.search.clearFilters':'清除全部篩選','travelpass.search.asia':'亞洲','travelpass.search.europe':'歐洲','travelpass.search.americas':'美洲','travelpass.search.africa':'非洲','travelpass.search.oceania':'大洋洲','footer.poweredBy':'由 Jiffoo 提供支援','footer.copyright':'版權所有 © {year} {brand}。保留所有權利。' });
Object.assign(themeMessages.en, { 'nav.explore': 'Explore', 'products.landingQuestion': 'Where are you landing?', 'products.nearby': 'Nearby', 'products.swipe': 'Swipe', 'travelpass.products.recentlyViewed': 'Recently viewed' });
Object.assign(themeMessages['zh-Hans'], { 'nav.explore': '探索', 'products.landingQuestion': '您要前往哪里？', 'products.nearby': '附近', 'products.swipe': '滑动浏览', 'travelpass.products.recentlyViewed': '最近浏览' });
Object.assign(themeMessages['zh-Hant'], { 'nav.explore': '探索', 'products.landingQuestion': '您要前往哪裡？', 'products.nearby': '附近', 'products.swipe': '滑動瀏覽', 'travelpass.products.recentlyViewed': '最近瀏覽' });
Object.assign(themeMessages.en, { 'products.webPlans': 'Web plans', 'products.heroTitle': 'Explore blue-sky eSIM plans without roaming chaos.', 'products.heroDescription': '{brand} keeps every plan crisp: destination, data, validity, carrier speed, and instant QR delivery in a clean white-card catalog.', 'products.searchPlaceholder': 'Search Tokyo, Paris, Global', 'products.qrReady': 'QR ready', 'products.5gSpeed': '5G speed', 'products.usdPricing': 'USD pricing', 'products.resetFilters': 'Reset filters', 'products.option_all_regions': 'All regions', 'products.option_7_days': '7 days', 'products.option_15_days': '15 days', 'products.option_30_days': '30 days', 'products.option_90_days': '90 days', 'products.option_unlimited': 'Unlimited' });
Object.assign(themeMessages['zh-Hans'], { 'products.webPlans': '网页套餐', 'products.heroTitle': '探索清爽的 eSIM 套餐，告别漫游混乱。', 'products.heroDescription': '{brand} 让每个套餐都清晰呈现目的地、流量、有效期、运营商速度和即时二维码交付。', 'products.searchPlaceholder': '搜索东京、巴黎、全球', 'products.qrReady': '二维码就绪', 'products.5gSpeed': '5G 速度', 'products.usdPricing': '美元定价', 'products.resetFilters': '重置筛选', 'products.option_all_regions': '所有地区', 'products.option_7_days': '7 天', 'products.option_15_days': '15 天', 'products.option_30_days': '30 天', 'products.option_90_days': '90 天', 'products.option_unlimited': '不限量' });
Object.assign(themeMessages['zh-Hant'], { 'products.webPlans': '網頁方案', 'products.heroTitle': '探索清晰的 eSIM 方案，告別漫遊混亂。', 'products.heroDescription': '{brand} 清楚呈現每個方案的目的地、流量、有效期、電訊商速度及即時 QR 交付。', 'products.searchPlaceholder': '搜尋東京、巴黎、全球', 'products.qrReady': 'QR 碼就緒', 'products.5gSpeed': '5G 速度', 'products.usdPricing': '美元定價', 'products.resetFilters': '重設篩選', 'products.option_all_regions': '所有地區', 'products.option_7_days': '7 天', 'products.option_15_days': '15 天', 'products.option_30_days': '30 天', 'products.option_90_days': '90 天', 'products.option_unlimited': '不限量' });
Object.assign(themeMessages.en, { 'products.plansAvailable': '{count} plans available', 'products.catalogHint': 'Blue-white cards, USD prices, and instant eSIM fulfillment.', 'products.gridView': 'Grid view', 'products.listView': 'List view', 'products.previous': 'Previous', 'products.next': 'Next' });
Object.assign(themeMessages['zh-Hans'], { 'products.plansAvailable': '共 {count} 个套餐', 'products.catalogHint': '蓝白卡片、美元价格和即时 eSIM 交付。', 'products.gridView': '网格视图', 'products.listView': '列表视图', 'products.previous': '上一页', 'products.next': '下一页' });
Object.assign(themeMessages['zh-Hant'], { 'products.plansAvailable': '共 {count} 個方案', 'products.catalogHint': '藍白卡片、美元價格及即時 eSIM 交付。', 'products.gridView': '網格檢視', 'products.listView': '清單檢視', 'products.previous': '上一頁', 'products.next': '下一頁' });
Object.assign(themeMessages.en, { 'home.webHome': 'Web - Home', 'home.instantQr': 'Instant QR delivery', 'home.countries': '190+ countries', 'home.support247': '24/7 support', 'home.viewAllDestinations': 'View all destinations', 'home.viewAllPlans': 'View all plans', 'home.from': 'From', 'home.whereData': 'Where do you need data?', 'home.anyAmount': 'Any amount', 'home.anyDuration': 'Any duration', 'home.travelers': 'Travelers', 'home.findPlans': 'Find plans', 'home.popularSearches': 'Popular searches:', 'home.trusted': 'Trusted by travelers', 'home.worldwide': 'worldwide', 'home.securePayments': 'Secure payments', 'home.dataProtected': 'Your data is protected by {brand}' });
Object.assign(themeMessages['zh-Hans'], { 'home.webHome': '网页 - 首页', 'home.instantQr': '即时二维码交付', 'home.countries': '190 多个国家', 'home.support247': '全天候支持', 'home.viewAllDestinations': '查看所有目的地', 'home.viewAllPlans': '查看所有套餐', 'home.from': '起价', 'home.whereData': '您需要哪里的流量？', 'home.anyAmount': '任意流量', 'home.anyDuration': '任意期限', 'home.travelers': '旅行人数', 'home.findPlans': '查找套餐', 'home.popularSearches': '热门搜索：', 'home.trusted': '深受旅行者信赖', 'home.worldwide': '遍布全球', 'home.securePayments': '安全支付', 'home.dataProtected': '您的数据由 {brand} 保护' });
Object.assign(themeMessages['zh-Hant'], { 'home.webHome': '網頁 - 首頁', 'home.instantQr': '即時 QR 交付', 'home.countries': '190 多個國家', 'home.support247': '全天候支援', 'home.viewAllDestinations': '查看所有目的地', 'home.viewAllPlans': '查看所有方案', 'home.from': '起價', 'home.whereData': '您需要哪裡的流量？', 'home.anyAmount': '任意流量', 'home.anyDuration': '任意期限', 'home.travelers': '旅客人數', 'home.findPlans': '尋找方案', 'home.popularSearches': '熱門搜尋：', 'home.trusted': '深受旅客信賴', 'home.worldwide': '遍佈全球', 'home.securePayments': '安全付款', 'home.dataProtected': '您的資料由 {brand} 保護' });
Object.assign(themeMessages.en, { 'home.mobileExplore': 'Mobile - Explore', 'home.searchDestinations': 'Search destinations', 'nav.more': 'More' });
Object.assign(themeMessages['zh-Hans'], { 'home.mobileExplore': '移动端 - 探索', 'home.searchDestinations': '搜索目的地', 'nav.more': '更多' });
Object.assign(themeMessages['zh-Hant'], { 'home.mobileExplore': '流動版 - 探索', 'home.searchDestinations': '搜尋目的地', 'nav.more': '更多' });
Object.assign(themeMessages.en, { 'auth.callback.failed': 'Authentication Failed', 'auth.callback.backToLogin': 'Back to Login', 'auth.callback.completing': 'Completing Sign In', 'auth.callback.waiting': 'Please wait while we complete your authentication...' });
Object.assign(themeMessages['zh-Hans'], { 'auth.callback.failed': '身份验证失败', 'auth.callback.backToLogin': '返回登录', 'auth.callback.completing': '正在完成登录', 'auth.callback.waiting': '请稍候，我们正在完成身份验证……' });
Object.assign(themeMessages['zh-Hant'], { 'auth.callback.failed': '身份驗證失敗', 'auth.callback.backToLogin': '返回登入', 'auth.callback.completing': '正在完成登入', 'auth.callback.waiting': '請稍候，我們正在完成身份驗證……' });

Object.assign(themeMessages.en, {
  'faq.gettingStarted.title': 'Getting Started', 'faq.gettingStarted.description': 'Learn how to purchase and activate your eSIM', 'faq.gettingStarted.q1': 'What is an eSIM?', 'faq.gettingStarted.a1': 'An eSIM is a digital SIM built into your device that can be programmed with carrier profiles.', 'faq.gettingStarted.q2': 'How do I activate my eSIM?', 'faq.gettingStarted.a2': 'Scan the QR code sent by email in Settings > Cellular > Add eSIM. Activation completes within minutes.', 'faq.gettingStarted.q3': 'Which devices support eSIM?', 'faq.gettingStarted.a3': 'Most recent iPhone, Samsung Galaxy, and Google Pixel devices support eSIM.',
  'faq.dataUsage.title': 'Data & Usage', 'faq.dataUsage.description': 'Questions about data plans, speed, and coverage', 'faq.dataUsage.q1': 'How fast is the data connection?', 'faq.dataUsage.a1': '4G/LTE and 5G speeds depend on your location and local carrier network.', 'faq.dataUsage.q2': 'Can I check my remaining data?', 'faq.dataUsage.a2': 'Open My eSIMs in your account to see real-time usage and balance.', 'faq.dataUsage.q3': 'What happens when my data runs out?', 'faq.dataUsage.a3': 'Top up anytime. Your connection pauses until more data is added or the plan renews.',
  'faq.billing.title': 'Billing & Payments', 'faq.billing.description': 'Payment methods, refunds, and invoices', 'faq.billing.q1': 'What payment methods do you accept?', 'faq.billing.a1': 'We accept major cards, PayPal, Apple Pay, and Google Pay.', 'faq.billing.q2': 'Can I get a refund?', 'faq.billing.a2': 'Unactivated eSIMs qualify for a full refund within 7 days. Contact support for help.', 'faq.billing.q3': 'How do I get a receipt?', 'faq.billing.a3': 'Receipts are emailed automatically and available in My Account.',
  'faq.troubleshooting.title': 'Troubleshooting', 'faq.troubleshooting.description': 'Solve common issues with your eSIM', 'faq.troubleshooting.q1': 'My eSIM is not connecting', 'faq.troubleshooting.a1': 'Enable data roaming, set the eSIM as your data line, and toggle airplane mode.', 'faq.troubleshooting.q2': 'The QR code is not scanning', 'faq.troubleshooting.a2': 'Scan a clear code displayed on another device or contact support.', 'faq.troubleshooting.q3': 'Can I use my eSIM on multiple devices?', 'faq.troubleshooting.a3': 'No. Each profile is tied to one device; contact support to transfer it.', 'faq.questions': '{count} questions', 'faq.stillNeedHelp': 'Still need help?', 'faq.supportAvailable': 'Our support team is available 24/7 to assist you.', 'faq.contactSupport': 'Contact Support',
  'footer.description': 'Global eSIM plans selected for fast setup, clear pricing, and confident arrivals.', 'footer.regions': '190+ regions', 'footer.secureCheckout': 'Secure checkout', 'footer.company': 'Company', 'footer.help': 'Help center', 'footer.contact': 'Contact', 'footer.needHelp': 'Need help before takeoff?', 'footer.disclaimer': 'USD pricing, instant delivery, no roaming contract.', 'footer.appDescription': 'Android eUICC management download page. For support, contact {email}.', 'footer.language': 'Language',
  'legal.privacy.intro': 'At TravelPass, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our eSIM services.', 'legal.terms.intro': 'Welcome to TravelPass. These terms and conditions outline the rules for using our eSIM services. By accessing this website, you accept these terms and conditions.'
});
Object.assign(themeMessages['zh-Hans'], {
  'faq.gettingStarted.title': '开始使用', 'faq.gettingStarted.description': '了解如何购买和激活 eSIM', 'faq.gettingStarted.q1': '什么是 eSIM？', 'faq.gettingStarted.a1': 'eSIM 是内置于设备的数字 SIM，可加载不同运营商的配置文件。', 'faq.gettingStarted.q2': '如何激活 eSIM？', 'faq.gettingStarted.a2': '在设置 > 蜂窝网络 > 添加 eSIM 中扫描邮件里的二维码，几分钟即可激活。', 'faq.gettingStarted.q3': '哪些设备支持 eSIM？', 'faq.gettingStarted.a3': '大多数新款 iPhone、Samsung Galaxy 和 Google Pixel 支持 eSIM。', 'faq.dataUsage.title': '流量与使用', 'faq.dataUsage.description': '了解套餐、速度和覆盖范围', 'faq.billing.title': '账单与支付', 'faq.billing.description': '支付方式、退款和发票', 'faq.troubleshooting.title': '故障排查', 'faq.troubleshooting.description': '解决 eSIM 常见问题', 'faq.questions': '{count} 个问题', 'faq.stillNeedHelp': '仍需要帮助？', 'faq.supportAvailable': '我们的支持团队全天候为您提供协助。', 'faq.contactSupport': '联系支持', 'footer.description': '精选全球 eSIM 套餐，设置快捷、价格透明，让旅途更安心。', 'footer.regions': '190 多个地区', 'footer.secureCheckout': '安全结算', 'footer.company': '公司', 'footer.help': '帮助中心', 'footer.contact': '联系我们', 'footer.needHelp': '出发前需要帮助？', 'footer.disclaimer': '美元定价、即时交付、无需漫游合约。', 'footer.appDescription': 'Android eUICC 管理应用下载页。如需支持，请联系 {email}。', 'footer.language': '语言', 'legal.privacy.intro': 'TravelPass 致力于保护您的隐私。本隐私政策说明您使用 eSIM 服务时，我们如何收集、使用、披露和保护您的信息。', 'legal.terms.intro': '欢迎使用 TravelPass。本条款说明 eSIM 服务的使用规则。访问本网站即表示您接受这些条款。'
});
Object.assign(themeMessages['zh-Hant'], {
  'faq.gettingStarted.title': '開始使用', 'faq.gettingStarted.description': '了解如何購買及啟用 eSIM', 'faq.gettingStarted.q1': '什麼是 eSIM？', 'faq.gettingStarted.a1': 'eSIM 是內建於裝置的數位 SIM，可載入不同電訊商設定檔。', 'faq.gettingStarted.q2': '如何啟用 eSIM？', 'faq.gettingStarted.a2': '在設定 > 行動服務 > 加入 eSIM 掃描電郵中的 QR 碼，數分鐘即可啟用。', 'faq.gettingStarted.q3': '哪些裝置支援 eSIM？', 'faq.gettingStarted.a3': '大多數新款 iPhone、Samsung Galaxy 和 Google Pixel 均支援 eSIM。', 'faq.dataUsage.title': '流量與使用', 'faq.dataUsage.description': '了解方案、速度及覆蓋範圍', 'faq.billing.title': '帳單與付款', 'faq.billing.description': '付款方式、退款及發票', 'faq.troubleshooting.title': '疑難排解', 'faq.troubleshooting.description': '解決 eSIM 常見問題', 'faq.questions': '{count} 個問題', 'faq.stillNeedHelp': '仍需要協助？', 'faq.supportAvailable': '我們的支援團隊全天候為您提供協助。', 'faq.contactSupport': '聯絡支援', 'footer.description': '精選全球 eSIM 方案，設定快捷、價格透明，讓旅程更安心。', 'footer.regions': '190 多個地區', 'footer.secureCheckout': '安全結帳', 'footer.company': '公司', 'footer.help': '說明中心', 'footer.contact': '聯絡我們', 'footer.needHelp': '出發前需要協助？', 'footer.disclaimer': '美元定價、即時交付、無需漫遊合約。', 'footer.appDescription': 'Android eUICC 管理應用程式下載頁。如需支援，請聯絡 {email}。', 'footer.language': '語言', 'legal.privacy.intro': 'TravelPass 致力於保障您的私隱。本私隱政策說明您使用 eSIM 服務時，我們如何收集、使用、披露及保護您的資料。', 'legal.terms.intro': '歡迎使用 TravelPass。本條款說明 eSIM 服務的使用規則。瀏覽本網站即表示您接受這些條款。'
});

Object.assign(themeMessages['zh-Hans'], { 'checkout.paypal':'PayPal', 'checkout.applePay':'Apple Pay', 'travelpass.search.mostRelevant':'最相关', 'travelpass.search.priceLow':'价格从低到高', 'travelpass.search.name':'名称', 'travelpass.search.topRated':'评分最高' });
Object.assign(themeMessages['zh-Hant'], { 'checkout.paypal':'PayPal', 'checkout.applePay':'Apple Pay', 'travelpass.search.mostRelevant':'最相關', 'travelpass.search.priceLow':'價格由低至高', 'travelpass.search.name':'名稱', 'travelpass.search.topRated':'評分最高' });
Object.assign(themeMessages.en, { 'contact.responseNotice':"We'll get back to you within 1 hour.", 'contact.namePlaceholder':'Your name', 'contact.emailPlaceholder':'you@example.com', 'contact.messagePlaceholder':'Describe your issue or question...' });
Object.assign(themeMessages['zh-Hans'], { 'contact.responseNotice':'我们将在 1 小时内回复您。', 'contact.namePlaceholder':'您的姓名', 'contact.emailPlaceholder':'you@example.com', 'contact.messagePlaceholder':'请描述您的问题...' });
Object.assign(themeMessages['zh-Hant'], { 'contact.responseNotice':'我們將在 1 小時內回覆您。', 'contact.namePlaceholder':'您的姓名', 'contact.emailPlaceholder':'you@example.com', 'contact.messagePlaceholder':'請描述您的問題...' });
Object.assign(themeMessages.en, { 'nav.home':'Home', 'header.currencyUsd':'Currency USD', 'nav.menu':'Menu' });
Object.assign(themeMessages['zh-Hans'], { 'nav.home':'首页', 'header.currencyUsd':'货币 美元', 'nav.menu':'菜单' });
Object.assign(themeMessages['zh-Hant'], { 'nav.home':'首頁', 'header.currencyUsd':'貨幣 美元', 'nav.menu':'選單' });
Object.assign(themeMessages.en, { 'nav.destinations':'Destinations', 'nav.esimPlans':'eSIM Plans', 'nav.howItWorks':'How it works', 'nav.forBusiness':'For business', 'nav.help':'Help' });
Object.assign(themeMessages['zh-Hans'], { 'nav.destinations':'目的地', 'nav.esimPlans':'eSIM 套餐', 'nav.howItWorks':'使用方式', 'nav.forBusiness':'商务合作', 'nav.help':'帮助' });
Object.assign(themeMessages['zh-Hant'], { 'nav.destinations':'目的地', 'nav.esimPlans':'eSIM 方案', 'nav.howItWorks':'使用方式', 'nav.forBusiness':'商務合作', 'nav.help':'說明' });
Object.assign(themeMessages.en, { 'header.usd':'USD', 'account.sampleData':'7.2 GB' });
Object.assign(themeMessages['zh-Hans'], { 'header.usd':'美元', 'account.sampleData':'7.2 GB' });
Object.assign(themeMessages['zh-Hant'], { 'header.usd':'美元', 'account.sampleData':'7.2 GB' });
Object.assign(themeMessages.en, { 'common.errorTitle':'Something went wrong', 'travelpass.categories.destinations':'Destinations', 'travelpass.categories.empty':'No destinations available', 'travelpass.deals.emptyTitle':'No Deals Right Now', 'travelpass.deals.emptyHint':'Check back soon for new offers!', 'travelpass.deals.limitedOffer':'Limited time offer', 'travelpass.deals.viewDeal':'View Deal' });
Object.assign(themeMessages['zh-Hans'], { 'common.errorTitle':'发生错误', 'travelpass.categories.destinations':'目的地', 'travelpass.categories.empty':'暂无可用目的地', 'travelpass.deals.emptyTitle':'目前没有优惠', 'travelpass.deals.emptyHint':'请稍后再来查看新优惠！', 'travelpass.deals.limitedOffer':'限时优惠', 'travelpass.deals.viewDeal':'查看优惠' });
Object.assign(themeMessages['zh-Hant'], { 'common.errorTitle':'發生錯誤', 'travelpass.categories.destinations':'目的地', 'travelpass.categories.empty':'暫無可用目的地', 'travelpass.deals.emptyTitle':'目前沒有優惠', 'travelpass.deals.emptyHint':'請稍後再來查看新優惠！', 'travelpass.deals.limitedOffer':'限時優惠', 'travelpass.deals.viewDeal':'查看優惠' });
Object.assign(themeMessages.en, { 'contact.emailLabel':'Email', 'contact.phoneLabel':'Phone', 'contact.liveChat':'Live Chat', 'contact.available247':'Available 24/7', 'contact.responseTime':'Response Time', 'contact.responseWithinHour':'Usually within 1 hour', 'contact.messageSent':'Message Sent!', 'contact.sendAnother':'Send another message', 'contact.sendMessageTitle':'Send us a message', 'contact.name':'Name', 'contact.subject':'Subject', 'contact.message':'Message', 'contact.sending':'Sending...', 'contact.sendMessage':'Send Message', 'account.expiresIn':'Expires in {days} days ({date})' });
Object.assign(themeMessages['zh-Hans'], { 'contact.emailLabel':'电子邮箱', 'contact.phoneLabel':'电话', 'contact.liveChat':'在线聊天', 'contact.available247':'全天候可用', 'contact.responseTime':'响应时间', 'contact.responseWithinHour':'通常 1 小时内', 'contact.messageSent':'消息已发送！', 'contact.sendAnother':'发送另一条消息', 'contact.sendMessageTitle':'给我们留言', 'contact.name':'姓名', 'contact.subject':'主题', 'contact.message':'消息', 'contact.sending':'发送中...', 'contact.sendMessage':'发送消息', 'account.expiresIn':'还有 {days} 天到期（{date}）' });
Object.assign(themeMessages['zh-Hant'], { 'contact.emailLabel':'電郵', 'contact.phoneLabel':'電話', 'contact.liveChat':'即時聊天', 'contact.available247':'全天候可用', 'contact.responseTime':'回覆時間', 'contact.responseWithinHour':'通常 1 小時內', 'contact.messageSent':'訊息已傳送！', 'contact.sendAnother':'傳送另一則訊息', 'contact.sendMessageTitle':'向我們留言', 'contact.name':'姓名', 'contact.subject':'主旨', 'contact.message':'訊息', 'contact.sending':'傳送中...', 'contact.sendMessage':'傳送訊息', 'account.expiresIn':'還有 {days} 天到期（{date}）' });
Object.assign(themeMessages.en, { 'travelpass.cart.subtotal':'Subtotal ({count} items)', 'cart.instantEmail':'Instant (Email)', 'cart.refundPolicy':'7-day refund policy' });
Object.assign(themeMessages['zh-Hans'], { 'travelpass.cart.subtotal':'小计（{count} 件）', 'cart.instantEmail':'即时（电子邮件）', 'cart.refundPolicy':'7 天退款政策' });
Object.assign(themeMessages['zh-Hant'], { 'travelpass.cart.subtotal':'小計（{count} 件）', 'cart.instantEmail':'即時（電郵）', 'cart.refundPolicy':'7 天退款政策' });

const EXTRA_MESSAGES: Record<Locale, Record<string, string>> = {
  en: { 'cart.package': 'eSIM Package', 'cart.delivery': 'Delivery', 'cart.secureCheckout': 'Secure checkout', 'cart.instantDelivery': 'Instant eSIM delivery', 'header.currency': 'Currency', 'contact.selectTopic': 'Select a topic', 'contact.activation': 'eSIM Activation Help', 'contact.connectivity': 'Connectivity Issues', 'contact.billing': 'Billing & Refunds', 'contact.account': 'Account Issues', 'contact.other': 'Other' },
  'zh-Hans': { 'cart.package': 'eSIM 套餐', 'cart.delivery': '配送', 'cart.secureCheckout': '安全结算', 'cart.instantDelivery': 'eSIM 即时交付', 'header.currency': '货币', 'contact.selectTopic': '选择主题', 'contact.activation': 'eSIM 激活帮助', 'contact.connectivity': '连接问题', 'contact.billing': '账单与退款', 'contact.account': '账户问题', 'contact.other': '其他' },
  'zh-Hant': { 'cart.package': 'eSIM 套餐', 'cart.delivery': '配送', 'cart.secureCheckout': '安全結帳', 'cart.instantDelivery': 'eSIM 即時交付', 'header.currency': '貨幣', 'contact.selectTopic': '選擇主題', 'contact.activation': 'eSIM 啟用協助', 'contact.connectivity': '連線問題', 'contact.billing': '帳單與退款', 'contact.account': '帳戶問題', 'contact.other': '其他' },
};

// One merged dictionary handed to the SDK chain; every Object.assign
// block above has run before this module-level merge.
const CHAIN_MESSAGES: Record<Locale, Record<string, string>> = {
  en: { ...themeMessages.en, ...EXTRA_MESSAGES.en },
  'zh-Hans': { ...themeMessages['zh-Hans'], ...EXTRA_MESSAGES['zh-Hans'] },
  'zh-Hant': { ...themeMessages['zh-Hant'], ...EXTRA_MESSAGES['zh-Hant'] },
};

export function localize(locale: Locale | undefined, key: MessageKey, fallback: string, params?: Record<string, string | number>): string {
  return sdkThemeText(undefined, locale, key, fallback, params, CHAIN_MESSAGES);
}

export function themeText(t: TranslationFunction | undefined, locale: Locale | undefined, key: MessageKey, fallback: string, params?: Record<string, string | number>): string {
  return sdkThemeText(t, locale, key, fallback, params, CHAIN_MESSAGES);
}
